### ISSUE TITLE
raw_high_lat parallel runs crash before reaching time loop

### ISSUE THREAD

**Issue by joeschoonover** [SWPC-IPE/WAM-IPE#100]
In a discussion relayed from Slack, quote from @IonospherePlasmasphereElectrodynamics  : 
"
after comparing 3 test runs((1) serial (2) parallel1 (3) parallel464 for 600s), serial finished successfully, while both parallel runs crashed immediately before time loop.

(2) parallel1 shows the error message:
```
forrtl: severe (67): input statement requires too much data, unit 5996, file /scratch3/NCEPDEV/swpc/noscrub/Naomi.Maruyama/wam-ipe_initial_conditions/T62_80x170/20151703_0000UT/IPE/ipe_grid_neutral_params
Image              PC                Routine            Line        Source             
ipe_theia_intel_p  00000000009F99F9  Unknown               Unknown  Unknown
```
"

In order to progress on Issue #43 , this bug needs to be resolved.

**Comment by IonospherePlasmasphereElectrodynamics** [comment]
the Tn shape is(1115,172,84) just before reading the neutral restart file. that is why the error message said "input statement requires too much data"

**Comment by joeschoonover** [comment]
Is this due to the way SMS decomposes data ?

**Comment by joeschoonover** [comment]
Note that the read statement for the neutral parameters is 
```
  READ (unit=5996) tn_k
  READ (unit=5996) vn_ms1_4output
  READ (unit=5996) on_m3 
  READ (unit=5996) n2n_m3
  READ (unit=5996) o2n_m3
```
where each of the fields is supposed to be of dimension (1115,170,80) except for the vn_ms1_4output which is (1115,170,80,3). At single precision, this means that we should expect the file ipe_grid_neutral_params to contain

1115 x 170 x 80 x 7 x 4  = 424,592,000 Bytes

If you do an `ls -l ipe_grid_neutral_params` in our ipe_initial_conditions folder, you'll see that the size of this file is 424,592,040 Bytes. The extra 40 bytes comes from the header information stored in the file that indicates the size of each record stored in the file. 

Because the read statement doesn't give an explicit shape, what happens is that the full array (with the added halo cells from SMS) should be read in. As you pointed out, this is larger than the (1115,170,80) that is expected.

**Comment by joeschoonover** [comment]
A good fix would be to do something like
```
  READ (unit=5996) tn_k(1:maxFluxTube,1:NLP,1:NMP)
  READ (unit=5996) vn_ms1_4output(1:maxFluxTube,1:NLP,1:NMP,1:3)
  READ (unit=5996) on_m3(1:maxFluxTube,1:NLP,1:NMP) 
  READ (unit=5996) n2n_m3(1:maxFluxTube,1:NLP,1:NMP)
  READ (unit=5996) o2n_m3(1:maxFluxTube,1:NLP,1:NMP)
```
It would also be a good idea to add the explicit array shapes to the write statement in `io_plasma_bin.f90` as well

**Comment by IonospherePlasmasphereElectrodynamics** [comment]
thanks joe for your suggestion. after the suggested fix, parallel 1prc run just past the reading the neutral restart file and went into the time loop.

**Comment by IonospherePlasmasphereElectrodynamics** [comment]
however, parallel 464prcs run remains to crash at the same location in plasma/io_plasma_bin.f90.

**Comment by joeschoonover** [comment]
Interesting. I suspect that SMS is not interpreting this region correctly. It’s possible that SMS is making (for example) an array that is smaller than (1115,170,80) due to domain decomposition. I’ll take a look at the sms interepreted code and start there

**Comment by joeschoonover** [comment]
Do we know if there are differences between io_plasma_bin.f90 on development ?

```
git  diff development io_plasma_bin.f90
```

**Comment by IonospherePlasmasphereElectrodynamics** [comment]
FYI: parallel 2prcs did not crash.

**Comment by IonospherePlasmasphereElectrodynamics** [comment]
found out my previous parallel 464prcs run had a problem.
now both parallel 2 and 464 prcs runs crashed at the same, new location:

https://github.com/SWPC-IPE/WAM-IPE/blob/raw_high_lat/IPELIB/src/eldyn/get_efield90km.f#L292

` sub-get_e:NH!STOP! INVALID           1           0           1         250
   6461200.      1.1770907E-43  3.4906585E-02
`

**Comment by joeschoonover** [comment]
Does the 464 process simulation get past io_plasma_bin ?

**Comment by IonospherePlasmasphereElectrodynamics** [comment]
yes. sorry for the confusion. i made a new parallel 464prc run. it past io_plasma_bin.

**Comment by joeschoonover** [comment]
can you push up the changes to io_plasma_bin.f90 ?

**Comment by joeschoonover** [comment]
also, since we've accomplished the goal of this issue (resolving the bug within io_plasma_bin), I'll make another issue (Issue #101) about the crash within electrodynamics using your above comment.

**Comment by joeschoonover** [comment]
raw_high_lat still cannot run past io_plasma_bin. 

I've confirmed that the PPP interpreter is not placing the appropriate scatter and gather calls around the read statements in io_plasma_bin and they are present on the development branch.

**Comment by joeschoonover** [comment]
I had to add the line 
```
ipe_f107_kp_mod ../main/ipe_f107_kp_mod.f90
```
to all of the `SMS_Module_Lookup.txt` files under each of the IPELIB/src subdirectories. Apparently, not having these dependencies handed to PPP causes this interpreter to not interpret the SMS directives into SMS source code. Now, io_plasma_bin is interpreted as expected. 

Still need to run check to verify that we get past the io_plasma_bin module

**Comment by joeschoonover** [comment]
Doing this also removed all of the SMS Errors during compilation

**Comment by joeschoonover** [comment]
I've verified that we succesfully get past io_plasma_bin, but now standalone IPE crashes within get_efield90km.f90 with the message : 
```
SMS: Abort Message=get_efield90km_sms.f90:122
```
Discussion of this new bug will be carried out in Issue #101
