### ISSUE TITLE
Add polar plots to Convert_mpi.batch workload

### ISSUE THREAD

**Issue by joeschoonover** [SWPC-IPE/WAM-IPE#112]
As part of the diagnostics, it would be helpful to have polar plots of the neutrals, plasmas, and TEC. To close this issue, add the appropriate python code to the post-processor to produce polar plots for the standard output on the raw_high_lat_branch

**Comment by akubaryk** [comment]
`43df4e5` introduces a polar stereographic option to the post-processor. There's a new user-configurable variable in Convert_mpi.batch, PLOTTYPE="-p" or "--polar" to produce (NH) polar plots, while leaving it blank will produce the traditional cylinder projection global plots.

Open to input on how to make this feature better or more usable.

**Comment by joeschoonover** [comment]
Excellent. can we close this issue ?
