### ISSUE TITLE
NetCDF for WAM

### ISSUE THREAD

**Issue by ZhuxiaoLi66** [SWPC-IPE/WAM-IPE#114]
Validate and merge the WAM NetCDF output feature created by Weiyu in SVN version (trunk_98231_work) to current development branch.

**Comment by ZhuxiaoLi0113** [comment]
As the first step, copied Weiyu's SVN code for runs to verify the algorithm and format of the WAM NetCDF output variables.  The current findings and the corresponding solutions are as following: 

1. Now Weiyu's NetCDF output is in Gaussian grid (same as sigma output format). Weiyu said he will try to interpolate the Gaussian grid to regular lat-lon grid, I point out the code of ss2gg to him for reference. 
2. I verified the algorithm for number density of O, O2, N2 in Weiyu's code (get_w_z.f) by deducing the formulas ,comparing with current diagnostic code and checking the output value range. They are correct. 
3. The algorithm for den and gmol have some problems. I suggest the reasonable formulas, will rethink it this morning. 
4. The current format of the NetCDF output, don't have dimension and attributes, will do further communication with Weiyu later.

**Comment by ZhuxiaoLi0113** [comment]
Re-duduced the formulas for den and gmol in get_w_z.f. discussed with Tim, Weiyu.

**Comment by ZhuxiaoLi0113** [comment]
[https://drive.google.com/drive/u/0/folders/145xUFLSGomdkVpyEhYjcWZ13hcsFMO-X](url)
The plots are the output from the WAM run with JouleHeating factoring + Vertical Eddy diffusion + new solar heating feature.

**Comment by ZhuxiaoLi0113** [comment]
get the agreement with Weiyu on the algorithm and attributes of the WAM NetCDF output (at pressure levels first).  submitted the request to add the attributes of the NetCDF files, also checking the possibility about the output regridding (from Gaussin to regular) by internal code.
