### ISSUE TITLE
Take a look through WAM output on the raw_high_lat branch

### ISSUE THREAD

**Issue by joeschoonover** [SWPC-IPE/WAM-IPE#119]
We need to take a look through the WAM output on the raw_high_lat branch to see how WAM is currently responding to storm-time.

- [ ] Perform a WAM standalone run (on the raw_high_lat branch) before and after a storm period.
- [ ] Provide the group with an assessment of your analysis.

**Comment by joeschoonover** [comment]
@twfang , periodically come up here and update us on your progress with this issue.

**Comment by joeschoonover** [comment]
@twfang , were you able to succesfully do the 10 day simulations we set up yesterday ?

**Comment by twfang** [comment]
The 10 day standalone WAM works fine with the restart on this branch. I will look into the outputs and see how WAM fields behave.

**Comment by twfang** [comment]
Once the time-varying drivers all go into WAM properly (#121), we will evaluate WAM results under quiet and storm conditions.

**Comment by ZhuxiaoLi66** [comment]
everyone, what is the most expected influence of the updates of current raw_high_lat branch on WAM output before our drivers_in codes?

**Comment by joeschoonover** [comment]
This sounds like a question for @twfang
