### ISSUE TITLE
Properly set up WAM to respond to solar wind drivers

### ISSUE THREAD

**Issue by joeschoonover** [SWPC-IPE/WAM-IPE#121]
At the developer's meeting on 2/5/2018, there was mention of the possibility that WAM currently is not set up to respond to drivers.

I need someone to more completely and accurately describe this issue and develop a task list for this.

@timfullerrowell @twfang

**Comment by akubaryk** [comment]
@ZhuxiaoLi66 let me know when you have a new branch off raw_high_lat available so I can add some new code relevant to the discussion we had on Friday.

**Comment by twfang** [comment]
duplicate issue with #126
