### ISSUE TITLE
Unnecessary files in the repository

### ISSUE THREAD

**Issue by schoonovernumerics** [SWPC-IPE/WAM-IPE#13]
There are a number of files that are generated during the build process of WAM-IPE that do not necessarily need to be a part of the repository. We need to generate a list of unnecessary files, add them to the .gitignore file, and remove them from the repository.

**Comment by akubaryk** [comment]
A variety of commits have resolved the NEMS *.f90/*.F90,  **/*.mk, and *INSTALL*/** issues. The repository should be very clean on the development branch, but we need to still be vigilant with branches based on older commit trees.
