### ISSUE TITLE
Run Coupled WAM-IPE with sw_neutral=3 and WAM neutral velocity

### ISSUE THREAD

**Issue by joeschoonover** [SWPC-IPE/WAM-IPE#142]
This issue stems from #115.

In #115, a test had been conducted with `sw_neutral=3` while running in coupled mode. @IonospherePlasmasphereElectrodynamics indicates that this switch results in IPE using MSIS neutral parameters but zero neutral wind velocity.  Based on the results of this test, we had arrived at the idea that the neutral densities produced by WAM are contributing to the large max TEC ( > 100 TECu ) in IPE. However, it is unclear how much of the structure of IPE changed as a result of effectively turning off the neutral wind.

To resolve this issue, the assigned developer should run a test with `sw_neutral=3` but with the neutral wind obtained from WAM. The code changes from this modification **should not** be committed to the repository. Plots of TEC, consistent with those shown in #115, should be made for 00UT, 08,UT 16UT, and 24UT to compare with the run in #115. The assigned developer should provide a summary of the results and suggest the next steps.

**Comment by IonospherePlasmasphereElectrodynamics** [comment]
Tzu-Wei and I discussed. The following steps are the strategy:
- [] find out why wind is zero in the standalone IPE runs.
