### ISSUE TITLE
Remove GPTL and SMS_Compare calls in IPLEIB

### ISSUE THREAD

**Issue by joeschoonover** [SWPC-IPE/WAM-IPE#146]
As part of the code cleanup effort, GPTL should be erradicated from the IPE code as it is not a publicly supported code and will make the sell to operations more difficult.  To resolve this issue

- [ ] All GPTL calls in the `IPELIB/` and `IPE/' directories should be removed.

Additionally, there are many instances of calling sms_compare that should not be around. These calls are primarily for debugging ( [based on the SMS manual](https://www.esrl.noaa.gov/gsd/ato/publications/SMS_UsersGuide_v2.9.pdf) ) and introduce some overhead (the exact amount is unclear )

- [ ] Remove any `sms_compare`  in IPELIB and IPE directories

- [ ] Remove the `IPELIB/src/dummygptl` directory and remove references to gptl in the make system

**Comment by joeschoonover** [comment]
Confirmed that after applying the FortranReformat script, removing gptl calls, and fixing a couple small compilation issues ( hash id 7b9ace2142c5d02e8f37d5330d519f142f3ae179 ), the branch `schoonover-issue146_remove-gptl-calls` is bit-for bit identical to development

**Comment by joeschoonover** [comment]
There are no `sms_compare` statements under the main directory.

**Comment by joeschoonover** [comment]
Confirmed that 1164d7591fc5d615bc5c9ed1a1540375bd6837a1 results in bit-for-bit identical results with development in WAM-IPE coupled mode ( 1hr simulation )

**Comment by IonospherePlasmasphereElectrodynamics** [comment]
Joe,

Thank you very much for removing the gptl calls.
Has the code sped up without the gptl calls?
Could you please suggest an alternative timing library we could use for wam-ipe? 
Thanks.
naomi

**Comment by joeschoonover** [comment]
Naomi, 
This work is not finished. Check the project board and you'll notice that this issue is still in the "Open" column. We don't need a timing library. Profilers that attach to the code after compiling provide necessary information. There's no purpose in timing code in production.
