### ISSUE TITLE
Possible inconsistency in apexDscalar

### ISSUE THREAD

**Issue by joeschoonover** [SWPC-IPE/WAM-IPE#148]
`IPELIB/src/main/module_init_plasma_grid.f90` calculates an array called `apexScalarD`. This array, as the comments point out, comes from Eq. 3.15 of 
_A.D. Richmond, 1995, "Ionosphere Electrodynamics Using Magnetic Apex Coordinates", J. Geomag. Geoelect., **47**, 191-212_

From that article, equation 3.15 shows apexDscalar as a vector magnitude. In `module_init_plasma_grid.f90`, however, the absolute value is used, where I believe a square-root should be used. 

```
            ! calculate D from eq 3.15: | d1 X d2 |
            a(1) = apexD(ii,lp,mp,east,1)
            a(2) = apexD(ii,lp,mp,north,1)
            a(3) = apexD(ii,lp,mp,up,1)
            b(1) = apexD(ii,lp,mp,east,2)
            b(2) = apexD(ii,lp,mp,north,2)
            b(3) = apexD(ii,lp,mp,up,2)

            ! calculate cross product   a X b
            c(1) = a(2)*b(3) - a(3)*b(2)
            c(2) = a(3)*b(1) - a(1)*b(3)
            c(3) = a(1)*b(2) - a(2)*b(1)
!---

            apexDscalar(i,lp,mp) = ABS ( c(1)*c(1) + c(2)*c(2) + c(3)*c(3) )
```

**Comment by IonospherePlasmasphereElectrodynamics** [comment]
Joe,

Thank you very much for your finding out the bug. I am really sorry I was not very careful in implementing it. Would you mind comparing the results(the usual TEC plots) between before and after the bug fix?

Thanks.
naomi

**Comment by joeschoonover** [comment]
Work hasn't started on this. Feel free to make the modification and contribute to the project
