### ISSUE TITLE
Too much output printed to screen

### ISSUE THREAD

**Issue by schoonovernumerics** [SWPC-IPE/WAM-IPE#15]
Printing output to screen or to file wastes cpu cycles.  If we want to squeeze every bit of performance out of the code, we should revisit what is being printed to screen and to log files. We should only be writing information that is necessary. As we address this issue, we should start by indicating what information we would like to keep in output files during operational runs. Additionally, we can set pre-processing keys to enable additional output to aid in debugging.

**Comment by joeschoonover** [comment]
This issue will be closed as a new set of tasks related to refactoring will be added.
