### ISSUE TITLE
Memory Issues in IPELIB : Correct Compile Time Warnings and errors.

### ISSUE THREAD

**Issue by joeschoonover** [SWPC-IPE/WAM-IPE#150]
@gmillward described a scenario in which removing a print statement in `IPELIB/src/eldyn/get_efield90km.f90` resulted in IPE producing different plasma output. This behavior is typically indicative of memory issues elsewhere in the code. To identify the cause of the issue, it is recommended that we enable compile time warnings with the intel compiler and address the warnings as they appear.

**Comment by joeschoonover** [comment]
When compiling with the `-warn all -check all -debug all` flags, Intel cannot compile the msis source code. It gives errors similar to what GNU complains about and then some. It seems that some issues need to be corrected within MSIS source code.
```
nrlmsise00.f90(591): warning #6717: This name has not been given an explicit type.   [VTST7]
      v2=vtst7(iyd,sec,glat,glong,stl,f107a,f107,ap,2) 
^
nrlmsise00.f90(591): error #7983: The storage extent of the dummy argument exceeds that of the actual argument.   [AP]
      v2=vtst7(iyd,sec,glat,glong,stl,f107a,f107,ap,2) 
-------------------------------------------------^
nrlmsise00.f90(601): warning #6717: This name has not been given an explicit type.   [GLOBE7]
        if(v2.eq.1..or.alast.le.zn1(1)) tinf=ptm(1)*pt(1)               &
^
nrlmsise00.f90(602): error #7983: The storage extent of the dummy argument exceeds that of the actual argument.   [AP]
     &  *(1.+sw(16)*globe7(yrd,sec,glat,glong,stl,f107a,f107,ap,pt))    
-------------------------------------------------------------^
nrlmsise00.f90(610): error #7983: The storage extent of the dummy argument exceeds that of the actual argument.   [AP]
     &   *(1.+sw(19)*globe7(yrd,sec,glat,glong,stl,f107a,f107,ap,ps))   
--------------------------------------------------------------^
nrlmsise00.f90(617): error #7983: The storage extent of the dummy argument exceeds that of the actual argument.   [AP]
     &  f107a,f107,ap,pd(1,4)))*pd(1,4)                                 
-------------------^
nrlmsise00.f90(623): warning #6717: This name has not been given an explicit type.   [GLOB7S]
         tn1(2)=ptm(7)*ptl(1,1)/(1.-sw(18)*glob7s(ptl(1,1))) 
^
nrlmsise00.f90(646): error #7983: The storage extent of the dummy argument exceeds that of the actual argument.   [AP]
     & ap,pd(1,3))                                                      
-------^
nrlmsise00.f90(668): warning #6717: This name has not been given an explicit type.   [DENSU]
      d(3)=densu(z,db28,tinf,tlb, 28.,alpha(3),t(2),ptm(6),s,mn1,zn1,   &
^
nrlmsise00.f90(683): warning #6717: This name has not been given an explicit type.   [DNET]
      d(3)=dnet(d(3),dm28,zhm28,xmm,28.) 
^
nrlmsise00.f90(691): error #7983: The storage extent of the dummy argument exceeds that of the actual argument.   [AP]
      g4 = sw(21)*globe7(yrd,sec,glat,glong,stl,f107a,f107,ap,pd(1,1)) 
-----------------------------------------------------------^
nrlmsise00.f90(714): warning #6717: This name has not been given an explicit type.   [CCOR]
      d(1)=d(1)*ccor(z,rl,hc04,zc04) 
^
nrlmsise00.f90(722): error #7983: The storage extent of the dummy argument exceeds that of the actual argument.   [AP]
      g16= sw(21)*globe7(yrd,sec,glat,glong,stl,f107a,f107,ap,pd(1,2)) 
-----------------------------------------------------------^
nrlmsise00.f90(748): warning #6717: This name has not been given an explicit type.   [CCOR2]
      d(2)=d(2)*ccor2(z,rl,hc16,zc16,hc216) 
^
nrlmsise00.f90(762): error #7983: The storage extent of the dummy argument exceeds that of the actual argument.   [AP]
      g32= sw(21)*globe7(yrd,sec,glat,glong,stl,f107a,f107,ap,pd(1,5)) 
-----------------------------------------------------------^
nrlmsise00.f90(805): error #7983: The storage extent of the dummy argument exceeds that of the actual argument.   [AP]
      g40= sw(21)*globe7(yrd,sec,glat,glong,stl,f107a,f107,ap,pd(1,6)) 
-----------------------------------------------------------^
nrlmsise00.f90(836): error #7983: The storage extent of the dummy argument exceeds that of the actual argument.   [AP]
      g1 = sw(21)*globe7(yrd,sec,glat,glong,stl,f107a,f107,ap,pd(1,7)) 
-----------------------------------------------------------^
nrlmsise00.f90(872): error #7983: The storage extent of the dummy argument exceeds that of the actual argument.   [AP]
      g14 = sw(21)*globe7(yrd,sec,glat,glong,stl,f107a,f107,ap,pd(1,8)) 
------------------------------------------------------------^
nrlmsise00.f90(907): error #7983: The storage extent of the dummy argument exceeds that of the actual argument.   [AP]
      g16h = sw(21)*globe7(yrd,sec,glat,glong,stl,f107a,f107,ap,pd(1,9)) 
-------------------------------------------------------------^
nrlmsise00.f90(914): warning #6717: This name has not been given an explicit type.   [SCALH]
      zsho=scalh(zmho,16.,tho) 
```

**Comment by joeschoonover** [comment]
At the time of this message there are 1886 warnings  

```
make >& make_output.txt
grep warning make_output.txt | wc -l
1886
``

**Comment by joeschoonover** [comment]
Of those, 533 warnings are present in `IPELIB/src/neutral/hwm93.f90` All of those warnings come from variables that have not been declared anywhere. Inserting `IMPLICIT NONE` at the top of the subroutines within this module results in errors. Fixing them requires each variable is declared.

**Comment by joeschoonover** [comment]
It may be possible to swap the hwm model with a newer (2014) version from NRL. I just forked the NRL [lib repo](https://github.com/SWPC-IPE/lib/tree/master/hwm) to our SWPC-IPE account.

**Comment by joeschoonover** [comment]
While running IPE standalone with the GNU compilers, I stumbled on a runtime error inside of `interpolate_flux_tube`. This could be benign, but it's worth looking into. @gmillward 
![screenshot from 2018-03-20 12-27-47](https://user-images.githubusercontent.com/31802478/37675438-d9ac932c-2c3a-11e8-9118-1ea0754b6999.png)

**Comment by IonospherePlasmasphereElectrodynamics** [comment]
Joe,
Thank you very much for your

**Comment by IonospherePlasmasphereElectrodynamics** [comment]
I am really sorry I clicked "close" by mistake, while I was trying to make a comment.

**Comment by IonospherePlasmasphereElectrodynamics** [comment]
Joe, 

Thank you very much for your investigating the compiling errors/warnings due to MSIS/HWM. They were often causing troubles but we were too scared to modify them. 
Updating HWM from 1993 to the latest 2014 version would be really great as it was in the wish list. But how long would it take to swap? Furthermore, would it be a good idea to make sure at first if the latest version will not generate as many compiler warnings? Do they provide a standalone driver to do a test compiling and running?
Thanks.

**Comment by joeschoonover** [comment]
@IonospherePlasmasphereElectrodynamics , it's in the code.. it's working now. The new versions generate 0 compiler warnings/errors. I encourage you to check out the forked repos for [msis](https://github.com/SWPC-IPE/msise00)  and [hwm14](https://github.com/SWPC-IPE/lib/tree/master/hwm)

I didn't make the swap solely because its on the wish list. Carefully read the descriptions above in this thread

**Comment by IonospherePlasmasphereElectrodynamics** [comment]
Joe

> I just forked the NRL lib repo to our SWPC-IPE account.

Thank you very much for forking.
However, I am not sure if we want to fork the code without sending an quick message to the developers, because we know them.

though, perhaps, forking may be a standard procedure on github today.

**Comment by joeschoonover** [comment]
Seriously ?

**Comment by joeschoonover** [comment]
IPE Standalone currently runs on the `joe_issue150` branch. Coupled WAM-IPE currently crashes with the error message : 
```
forrtl: severe (193): Run-Time Check Failure. The variable 'module_neutral_mks_mp_neutral_$MIDPOINT' is being used without being defined
```

**Comment by joeschoonover** [comment]
Checked coupled model output at hash id 9bb4c77ea4b5d9b3299796df17f421d0cc08768a.  So far all looks good. I need to finish declaring implicit data in `nrlmsis00_sub.f`

**Comment by joeschoonover** [comment]
there are 608 warnings from `nrlmsise00_sub.f` due to implicitly defined data

**Comment by joeschoonover** [comment]
Removing these remaining warnings is not deemed a high priority relative to other open issues. Pull Request #153  has been opened to merge in changes described in this branch.
