### ISSUE TITLE
Undefined midpoint variable used in module_neutral_mks

### ISSUE THREAD

**Issue by rmontuoro** [SWPC-IPE/WAM-IPE#152]
Variable `midpoint` is used without being defined in a statement meant to address early issues in the neutral wind in the geomagnetic frame (`Un_ms1`) stemming from inappropriate D1/3 values:

https://github.com/SWPC-IPE/WAM-IPE/blob/f9cccf266ee5483f9d6b8b297a6de4699e59b041/IPELIB/src/neutral/module_neutral.f90#L280-L281

This issue can be quickly resolved by defining `midpoint` as in line:
https://github.com/SWPC-IPE/WAM-IPE/blob/f9cccf266ee5483f9d6b8b297a6de4699e59b041/IPELIB/src/neutral/module_neutral.f90#L142
but I'd like to verify that the above statement is still needed in IPELIB.

**Comment by joeschoonover** [comment]
Pull request #153 will fix the uninitialized value problem. Closing this issue
