### ISSUE TITLE
Add new real time data component to system

### ISSUE THREAD

**Issue by oehmke** [SWPC-IPE/WAM-IPE#157]

**Comment by oehmke** [comment]
It won't let me edit the initial description, so I'll just put it here. The idea is to add a new component that will read real time data and pass it along to WAM. The run sequence will be set up so that WAM has a dependency on the component and so won't move forward unless the new component has completed reading the data and passing it along. As a first pass I am just going to  create an empty prototype component that just runs at the correct time. After that's working  George can help me fill in the details of reading the data, etc.

**Comment by akubaryk** [comment]
Closed in favor of #295.
