### ISSUE TITLE
Assess Coupled WAM-IPE Run-length capability

### ISSUE THREAD

**Issue by joeschoonover** [SWPC-IPE/WAM-IPE#175]
Aim for a five day run with coupled WAM-IPE on the head of raw_high_lat_v3 branch.

We want to be able to answer whether or not WAM-IPE produces the same FLIP Error messages, or crashes at the same simulation time as coupled WAM-IPE.

 Provide an assessment of your experience with running WAM-IPE. Where necessary, provide model plots, standard output messages, and standard error messages, or other log files

**Comment by twfang** [comment]
The coupled WAM-IPE from raw_high_lat_v3 branch run through 5-day without problems!

**Comment by joeschoonover** [comment]
@twfang, are we good with closing this issue now that PR #155 is closed ?

**Comment by twfang** [comment]
Yes. Let's close the issue.
