### ISSUE TITLE
Validate the current WAM physics possibly related to the issue that TEC of WAM-IPE is too high

### ISSUE THREAD

**Issue by twfang** [SWPC-IPE/WAM-IPE#179]
To establish the baseline of WAM-IPE results under current version of development branch.

**Comment by ZhuxiaoLi66** [comment]
The result is consistent with the O/N2 from the new physics, the following plot is a former one, new plot with all physics update will come soon. 
![o_to_n2_wam_msis_f120_135lev_201301_kmax_160](https://user-images.githubusercontent.com/22546571/39772379-a55026ea-52e4-11e8-862b-424435c213b4.png)

**Comment by ZhuxiaoLi66** [comment]
The following O/N2 plot is for 201304 monthly mean at 250km by WAM_JH0_5 run and MSIS.
![o_to_n2_wam_msis_f120_kp3_135lev_201304_jh0_5_cb8](https://user-images.githubusercontent.com/22546571/39785899-7afa44d8-530d-11e8-9514-d83469af708b.png)

**Comment by ZhuxiaoLi66** [comment]
it is consistent with our O/N2 from the new physics, the plot is a former one, new plot with all physics update will come soon.

**Comment by IonospherePlasmasphereElectrodynamics** [comment]
Tzu-Wei,

Thank you very much for your new run with the new WAM startup files.

here is a new comparison just before the storm at 6UT 2013-03-17. 
The peak value looks comparable to the observation, although the equatorial ionization anomaly does not have two distinct peaks which is the issue we are still working on with regards to the perpendicular transport.
<img width="1280" alt="screen shot 2018-05-09 at 12 55 42 am" src="https://user-images.githubusercontent.com/13737186/39828946-12885dfa-537a-11e8-8d04-306cbea91fa8.png">



The peak value of the SED plume/TOI at 19UT looks closer to that of the GPS observation.
<img width="987" alt="screen shot 2018-05-09 at 1 07 30 am" src="https://user-images.githubusercontent.com/13737186/39828956-1c03e0fc-537a-11e8-977e-ef7c965ea625.png">
