### ISSUE TITLE
Add code to run interpolate script for IPE standalone ( for qsubipe )

### ISSUE THREAD

**Issue by joeschoonover** [SWPC-IPE/WAM-IPE#181]

**Comment by akubaryk** [comment]
Resolved with 78695a7, and a pull request is open -- I'm going to have it on my radar by the end of this week to incorporate IPE standalone into the normal run system, though. The `qsubipe` script is a bit unwieldy for portability concerns, and it would ease changes to the workflow from needing to be introduced to both sets of scripts.
