### ISSUE TITLE
Development tip run with fixed F107&KP get too high tempeture compared with original WAM latest Phyisics run and MSIS

### ISSUE THREAD

**Issue by ZhuxiaoLi66** [SWPC-IPE/WAM-IPE#186]
The run with fixed F107(120)&KP(3) by  Development tip branch get much higher temperature at high altitudes compared with original WAM latest Phyisics run and MSIS (please see the plots below). 

Code directory: /scratch3/NCEPDEV/swpc/save/Zhuxiao.Li/git/WAM-IPE/
run script: user.config_new_0320_fix_ann
work directory: /scratch3/NCEPDEV/swpc/scrub/Zhuxiao.Li/PTMP/dev_tip_new_fix_20120320_ann
divers file: /scratch3/NCEPDEV/swpc/scrub/Zhuxiao.Li/WAM_output/dev_tip_new_fix_20120320_ann/wam_input_f107_kp.txt

**Comment by ZhuxiaoLi66** [comment]
![wam-ipe_2d_135lev_t_dev_tip_fix_f107_kp_v3_physics_cb](https://user-images.githubusercontent.com/22546571/40321779-b35044ba-5d1f-11e8-9860-04cb046a0d4c.png)
![monthly_zonal_mean_t_solar1_eddy_140_jh0_5_co2_wam-msis_f120_2014_4](https://user-images.githubusercontent.com/22546571/40321796-c306bb46-5d1f-11e8-94a6-4412c357e0be.png)

**Comment by akubaryk** [comment]
What is the ROTDIR/PTMP directory for the "old v3" run? If we can identify the commit id for that version, we can see the explicit code differences in WAM between the two runs. I don't know what may need to be re-tuned to get acceptable results.

**Comment by ZhuxiaoLi66** [comment]
/scratch3/NCEPDEV/swpc/scrub/Zhuxiao.Li/PTMP/ann_solar1_eddy_140_JH0_5_co2
I should say the run is applying the old namelist way to run the latest WAM physics in V3.

**Comment by akubaryk** [comment]
There are namelist differences, but also 6 months of commits to WAM (that version of WAM seems to be mostly from November according to `git log`, although there are uncommitted changes in that WAM-IPE directory). Also the run in that directory started on 2013101100 while the original work directory is 2013032000.

I'm not sure I totally understand the comparison, but if there's any way I can help resolve this issue, please let me know.

**Comment by ZhuxiaoLi66** [comment]
@akubaryk , while WAM physics should be late than November, some times I revised the physics manually for the physically consistence results. the IC of 2013032000 run is form the original run, the different factors can't explain the large difference. Tzu-Wei mentioned that some parameters in new drivers file are different from the original setting in the code and namelist, that might be the reason.

**Comment by twfang** [comment]
Two tests of standalone WAM were carried out to identify if the high temperature in WAM is associated with the setting of IME clock angle. The default setting is 180 degree when IMB Bz is negative and 0 degree when IMF Bz is positive. However, the older version of WAM always set By=0, which leads to angle=tan(By/Bz)=0. Therefore, it is necessary to carry out the test. The simulation starts from 20130316 and the result in 20130430 is shown here. 

![wam_clockangle_comp](https://user-images.githubusercontent.com/22968399/40427958-6386991e-5e5c-11e8-81f7-5b20a45eeb75.png)

The figure shows that when using clock angle=0 for the fixed driver run, thermosphere temperature at level 135 became much cooler. The result looks very reasonable. This results suggest that we need to reconsider the clock angle that are currently set up in the script!

**Comment by akubaryk** [comment]
This is the relevant code from `scripts/interpolate_input_parameters/sw_from_f107_kp.py` (produced from [this comment](https://github.com/SWPC-IPE/WAM-IPE/issues/126#issuecomment-374304207)):

```
def swang_calc(bz):
  if bz >= 0.0:
    return 0.0
  else:
    return 180.0

def swby_calc():
  return 0.0

def swbz_calc(kp,f107):
  return -0.85*kp**2 - 0.081*kp + 0.434 + 0.0079 * f107 + 0.0022 * kp * f107
```

Gives a Bz = -5.719 and so a solar wind angle of 180 for F10.7=120, Kp=3. Can be as easy as returning 0.0 from `swang_calc`.

**Comment by twfang** [comment]
Let's let @timfullerrowell make a decision on this. He is travelling this week. We should talk about this at the Monday meeting next week.

**Comment by ZhuxiaoLi66** [comment]
As the information for you all,  the related WAM' original code is as following, 
     if( by == 0. .and. bz == 0.) then
         angle = 0.
      else
         angle = atan2( by,bz )
      end if
    angle = angle*rtd         ! radiance to degree
Based on the code, atan2(0, -5.719) = 3.1415926, should be 180 deg. 

Maybe Tzu-Wei will do some further tests.

**Comment by akubaryk** [comment]
We can reimplement the same code... Python also has a `math.atan2` function that handles the edge case of Bz=0.0:
```
>>> math.atan2(0.0,0.0)*180/math.pi
0.0
>>> math.atan2(1.0,0.0)*180/math.pi
90.0
>>> math.atan2(2.0,0.0)*180/math.pi
90.0
>>> math.atan2(0.0,-5.719)*180/math.pi
180.0
```
With special note to Zhuxiao's comment on swang=180.

**Comment by twfang** [comment]
I think I found the problem. Adam did implement the equation Tim provided correctly, which is  

**SW_Bz = -0.85 * Kp_squared - 0.081* Kp + 0.434 + 0.0079 * F10.7(daily) + 0.0022 * Kp * F10.7(daily)**

However, in idea_ion.f in WAM, bz has long been calculated using the following equation:

 **bz = .433726 - kp*(.0849999*kp + .0810363)+ f107d*(.00793738 - .00219316*kp)**

If you look carefully, the value 0.85 is one order of magnitude larger that 0.084. The sign for the last term is also opposite. Using the same Kp=3 and F107=120, the top equation gives -5.719 while the bottom equation gives -0.41. @timfullerrowell we need to look at the reference again and make sure the equation is implemented correctly. 

Sorry that I didn't catch this when I checked Adam's code. And the high-temperature should be directly related to the value instead of the clock angle that I posted early today!

**Comment by twfang** [comment]
I have submitted a new run after modifying the bz calculation in scripts/interpolate_input_parameters/sw_from_f107_kp.py. Will update tomorrow with the results.

**Comment by ZhuxiaoLi66** [comment]
I also throw a similar run (revise in Adam's python code) with the same IC file as my former run, let us wait for the results.

**Comment by timfullerrowell** [comment]
Well spotted Tzu-Wei.
That makes perfect sense now.
I sent the wrong information to Adam.
My bad!

**Comment by ZhuxiaoLi66** [comment]
At 42th hour, the max T value though all the levels with py code revise (Bz) run is 1165K, and the corresponding T in the former run (without Bz code revise) at the same time is already goes up to 1371K.  
in the current run, the corresponding Bz value in drivers file also goes down from -5.719 to about -0.4.

**Comment by twfang** [comment]
WAM standalone run suggested that the Bz is the main cause for the overestimation of the temp. We need to correct the equation used in scripts/interpolate_input_parameters/sw_from_f107_kp.py. @akubaryk , Tim is traveling this week. I would like to double check the numbers in the reference that he has before we modify the equation. Let's wait till next Tuesday!

![wam_bz_comp](https://user-images.githubusercontent.com/22968399/40486255-fee2e036-5f1d-11e8-9ba7-05a7e7d518fc.png)

**Comment by timfullerrowell** [comment]
I think it was a simple typo on my part.
The equation should be the same as in the Weimer code, so I think you can
edit.

**Comment by ZhuxiaoLi66** [comment]
The following plots verifies our correction. so I would like to close this issue later.
after Bz code correction,
![wam-ipe_2d_135lev_t_dev_tip_fix_f107_kp_bz_correct_cb](https://user-images.githubusercontent.com/22546571/40501476-81183160-5f77-11e8-9eee-32a2d0c0712d.png)

**Comment by twfang** [comment]
<img width="957" alt="screen shot 2018-05-30 at 10 21 51 am" src="https://user-images.githubusercontent.com/22968399/40733618-50273a58-63f3-11e8-8d92-e709f0a5d0f0.png">
@akubaryk , can we get it corrected asap? Thank you very much!

**Comment by akubaryk** [comment]
Branch `swang_bz_fix` has been created with this fix (and a now-dynamic assignment of the solar wind angle should we ever use a non-zero By). Should we open a pull request?

**Comment by twfang** [comment]
I think so. Let's get the change in. Thanks for getting this done!
