### ISSUE TITLE
Check output of Auroral_Precipitation in refactored IPE code

### ISSUE THREAD

**Issue by joeschoonover** [SWPC-IPE/WAM-IPE#190]
Auroral Precipitation routine has been added to IPE_Plasma_Class.F90. This subroutine is meant to replace `IPELIB/src/flip/sub_tiros_ionize_ipe.f` and `IPELIB/src/flip/sub_ionize_ipe.f` 

I need some help in assessing the correctness of this routine's output. Currently, the regridded NetCDF files contain the total ionization rate, O+, O2+, and N2+ ionization rates, in addition to the neutral densities produced from MSIS.  I have some output available already - if you'd like to learn how to run the test program, I can provide instructions also.

**Comment by IonospherePlasmasphereElectrodynamics** [comment]
Joe,
Thank you for working on the aurora routine.
I have the original standalone test with the original routines from @timfullerrowell on theia:
/home/Naomi.Maruyama/aurora/20150810/
You might be interested to use it as a baseline for your future development test.

**Comment by timfullerrowell** [comment]
Thanks Naomi,
That would be the best thing to compare with.

Joe, Let me know if you want me to look at some results.
Tim

**Comment by joeschoonover** [comment]
I'll get together a 24 hr cycle of ionization rate output. Should be ready tomorrow for your inspection. Are you ok looking through netcdf files ?

**Comment by timfullerrowell** [comment]
I use Panoply to view, so should be OK.

**Comment by joeschoonover** [comment]
Where should I package up and send the NetCDF files ?

**Comment by timfullerrowell** [comment]
Does google drive work?

**Comment by joeschoonover** [comment]
It does. it will take ~50 minutes to upload and ~50 minutes to download. I'll send a link by e-mail when it's posted.

**Comment by joeschoonover** [comment]
There were a couple concerns I had while porting this routine

1) The original wrapper ( sub_ionize_ipe.f ) only ionized flux tubes up to the flux tube midpoint - this resulted in only northern hemisphere ionization

2) The "gravity acceleration" (IGR index of plasma_grid_3d) passed into sub_tiros_ionize_ipe.f originally had been multiplied by a factor of "sinI"  ( z component of the 3rd apex vector divided by the apex vector magnitude ). Near the equator, the routine that returns sinI results in sinI=0, hence a gravitational acceleration equal to 0. In the ionization routine, when dividing by, what looks like a hydrostatic pressure, this causes division by zero.

Because of these issues, the refactored code does not have the sinI factor in the gravitational acceleration, and the ionization is done from 1 up to "max_flux_tube(lp)", the last used point on each of the flux tubes.

**Comment by IonospherePlasmasphereElectrodynamics** [comment]
Joe, 
Thank you very much. 
Here is a very simple way to make sure that the aurora routine is working. Attached is a comparison of E-region electron density (~120km) between with (top) vs. without (bottom) the auroral precipitation.
![fig1 v0](https://user-images.githubusercontent.com/13737186/40889413-52a73480-6723-11e8-81a7-72a0b9a9c0ff.png)

**Comment by joeschoonover** [comment]
After some dimension conversion corrections, removal of sinI factor in gravitational acceleration, I am able to get total ionization rate peak around 100-130 km altitude. Maximum is ~9 x 10^9 for the total ionization rate; still not sure what units are on these.

Closing this issue
