### ISSUE TITLE
check NO cooling related codes in WAM 

### ISSUE THREAD

**Issue by ZhuxiaoLi66** [SWPC-IPE/WAM-IPE#209]
Since the atmos. cooling speed in WAM is kind of slow at about 250km after storm warming during 20130317 storm time compared with GOCE satellite data and CTIPe, we plan to double check the NO cooling related codes in WAM to try to figure out the reason.

**Comment by ZhuxiaoLi66** [comment]
we checked the out print of NO cooling rate in idea_solar_heating.f, it seems that rate magnitude at high altitude (about lev 105 and peaked around lev120 is fine), we are doing the further check on the NO cooling rate day.vs.night side comparison.

**Comment by ZhuxiaoLi66** [comment]
Now I am checking the NO cooling related code in WAM (Valery revise version), and comparing it with the original code in CTIPe, try to verify all the changes and find the reason for the difference.  
we are also trying to output NO cooling rate from WAM to do the direct comparison with CTIPe.

**Comment by ZhuxiaoLi66** [comment]
With Houjun's help, found the way to output the NO cooling rate as a diagnostic variable (double checked the output path in the WAM code with Houjun). Already got the output of two SWIN runs for 2013 St. storm period (2013030100-2013032000), one with the new physics scheme, one without. will do some comparison with CTIPe output.

**Comment by akubaryk** [comment]
[Here's a by-timestep video of the NO cooling during a storm-time response](https://drive.google.com/open?id=1AcfUyVeN3zmn-hb3oG2iEnaGshWzOWpS) done with the static_nsphys branch. I can add/change components of the animation if there are any requests.

**Comment by ZhuxiaoLi66** [comment]
great job, Adam! Thanks for the great help! talk with you later.

**Comment by timfullerrowell** [comment]
This all looks very reasonable. Thanks Adam.
Are you able to change the max on the scale to say 0.015, so it brings out
the blue?

The increase at 19:45 agrees with the increase in CTIPe.
The values from CTIPe I looked at are in J m-3 s-1, 8e-9.
Divide by neutral mass density about 10e-9 kg m-3 and Cp ~1000 we get
similar numbers ~.0008 K/s.

Are you able to plot in the CTIPe units, x rho (neutral mass density) x Cp
(specific heat),
or are they not available locally?

Let's also compare the temperature and density with CTIPe, and density with
GOCE.
Hopefully the bug fix has corrected it.

**Comment by akubaryk** [comment]
PTMP: /scratch4/NCEPDEV/stmp3/Adam.Kubaryk/no_cool_DNS
RUNDIR: /scratch4/NCEPDEV/stmp4/Adam.Kubaryk/no_cool_DNS

code: /scratch3/NCEPDEV/swpc/save/Adam.Kubaryk/WAM-IPE/no_cooling_nc4

The 48 hour run ([video here](https://drive.google.com/open?id=1KNeKgl7dMj3qgnz-wx0lVhcFVSfrFyE3)) takes about 14 minutes with every-timestep output of one full-model physics field. I changed the color scale so hopefully there's some more obvious separation between high and low values. Apologies for the plots on the right cutting off after 1 day, I forgot to change those when I made the new plots.

I can only pull neutral mass density hourly as-is, but we could change the calculation inside the model code assuming the appropriate arrays (O, O2, ?) are exposed to the solar heating routine that calls wam_coolno1 -- as is, it's reporting qno/(cp*ro) where qno is the raw output for wam_coolno1.

**Comment by akubaryk** [comment]
I can output the raw qno instead, yes -- would we rather something else, though? Will go with a bolder colormap for the next one.

**Comment by timfullerrowell** [comment]
At the moment the plots are just for comparison with CTIPe, I think the qno
is J m-3 s-1, which is the same as CTIPe units.

**Comment by akubaryk** [comment]
OK -- should have that in about an hour.

**Comment by akubaryk** [comment]
Video [here](https://drive.google.com/open?id=1YD2hDiDNmwA3T1AFeQfyqt3Lo4WGdHmq).

Looked like the values peak around model level 114 so [I have one for that, too](https://drive.google.com/open?id=1bJw58sQNDkIWDMCo774Lx6RVSbAtEQy_), shows a bit more dramatically on the color scale.

**Comment by joeschoonover** [comment]
We discussed at today's developer meeting that this should be closed. Could someone provide reasoning why we're happy closing this issue?

**Comment by akubaryk** [comment]
The general scaling and jumps in the NO cooling field in the second video I linked in my most recent comment correspond well to an [animation of CTIP](https://drive.google.com/open?id=1x2xajSpofotCSv7d9d7LEzEkBf6JtbNp) for the same date provided by Tim. Therefore, we are satisfied that there's no problem with the NO cooling codes in particular, and can close this issue.
