### ISSUE TITLE
Conductivity Calculation

### ISSUE THREAD

**Issue by joeschoonover** [SWPC-IPE/WAM-IPE#215]
Convert the old field_line_integrals routine to the new refactored format. 

Establish a method for verifying this routine

**Comment by twfang** [comment]
The old code has been put in place in IPE_Plasma_Class.F90. It needs to be rewritten into the ipe_refactor format.

**Comment by twfang** [comment]
Codes for calculating field-line integrals are written and tested. All the new edits can be found in IPE_Plasma_Class.F90 in the IPE_electrodynamics branch. New codes are compiled and running smoothly in the branch. I have briefly looked at these integrals, their magnitudes are within the ranges that I expected. Will do more validation before feeding them into the dynamo solver.

**Comment by twfang** [comment]
MPI version of the conductivities calculation has been completed. MPI run and serial run provide the same answers to the dynamo solver. The issue will be closed
