### ISSUE TITLE
Add Read routine for Geospace

### ISSUE THREAD

**Issue by joeschoonover** [SWPC-IPE/WAM-IPE#222]
Add a reader that reads in files output by Geospace and  returns electric potential on it's native coordinate system

**Comment by joeschoonover** [comment]
We've added a netcdf reader for the Geospace model - @twfang keep us posted on testing of this routine . It would be good to close this issue before the weekend and hopefully move quickly to #223.

**Comment by twfang** [comment]
A new github branch called ipe_geospace has been created for adding the interface with Geospace model. 

Geospace model provides global electrical potentials in netcdf format. A new subroutines that reads in the Geospace outputs (SUBROUTINE Read_Geospace_Potential) has been added in IPE_Electrodynamics_Class.F90 and successfully provides correct potential and grid information to IPE.
