### ISSUE TITLE
Add Regrid routine for Geospace

### ISSUE THREAD

**Issue by joeschoonover** [SWPC-IPE/WAM-IPE#223]
Add routine that takes in electric potential on geospace grid and interpolates to IPE Grid (at 90 km altitude)

**Comment by joeschoonover** [comment]
@twfang @IonospherePlasmasphereElectrodynamics 

As a part of #201, I've added a routine under `src/IPE_Electrodynamics_Class.F90` called `Regrid_Potential`. This routine maps electric potential from a structured grid of ( mlt, colatitude) to the IPE grid. You may be able to use this routine for mapping Geospace output to the IPE grid, instead of writing your own routine. Let me know if you want help using this routine

**Comment by twfang** [comment]
Through using  "SUBROUTINE Regrid_Potential" we can properly map potential from Geospace to IPE grid. The work is currently in progress.

**Comment by twfang** [comment]
The potential from Geospace model has been successfully mapped from 110 km to 90 km and regrid onto IPE grid.
