### ISSUE TITLE
BDSLV Error messages

### ISSUE THREAD

**Issue by joeschoonover** [SWPC-IPE/WAM-IPE#229]
BDSLV routine currently throws two errors :
```
IN BDSLV &&&&&&& BANDWIDTH IS TOO LARGE         1
```
and 
```
IN BDSLV &&&&&&&&   ZERO PIVOT ELEMENT         1
```

We need to investigate, understand, and possibly correct the cause of theses errors

**Comment by joeschoonover** [comment]
Currently, the only "BDSLV" error that is apparent is : 
```
    IN BDSLV, ROW     1 IS ZERO IN INPUT MATRIX1=         1
```
which occurs for lp=169 for all mp.

**Comment by gmillward** [comment]
Yeh, I’ll take a look at that today - do you have advection turned off for < 150km?

**Comment by joeschoonover** [comment]
Yes. If you bring down the latest in ipe_refactor, this has advection turned off below 150 km altitude.

**Comment by joeschoonover** [comment]
Flux tube, lp=169 is the only offending flux tube, but does not result in unrealistic solutions at the equator. This is known and considered benign
