### ISSUE TITLE
incorrect physics timestepping wrt idea_phys

### ISSUE THREAD

**Issue by cajuncook** [SWPC-IPE/WAM-IPE#252]
The GSM uses a physics time-stepping scheme that takes the central difference between the base state and the physics state one step after the target timestep -- although my understanding of this is still nascent (Valery has offered [Gross et al. 2018](https://journals.ametsoc.org/doi/abs/10.1175/MWR-D-17-0345.1) for reference), I believe this brings the physics calculation more in line with the 3-step "leap-frog" Eulerian dynamics.

In do_physics_one_step.f:
```
      lsfwd   = kdt == 1
      phydt   = deltim
      if(.not. semilag .and. lsfwd) phydt = 0.5*deltim
```
and then in gloopb.f (phydt passed as tstep):
```
      nsphys = max(int((tstep+tstep)/dtphys+0.9999),1)
      dtp    = (tstep+tstep)/nsphys
      dtf    = 0.5*dtp
      if(lsfwd) dtf = dtp
```

Assuming a dynamics timestep DELTIM=180,
for **kdt=1**, lsfwd=.true., phydt/tstep = 0.5*180 = 90.0, and then **nsphys=1**, **dtp=180**, **dtf=180**
and for **kdt>1**, lsfwd=.false., phydt/tstep = 180, **nsphys=2**, **dtp=180**, **dtf=90**

Critical to this issue, the idea_phys call in gloopb occurs *before* the `do nn=1,nsphys` loop which contains gbphys, meaning the idea_phys tendencies have been wrong all along: gbphys is called twice with dtp=DELTIM, while idea_phys is called once with dtp=DELTIM.

It turns out the effect is actually quite severe. devWAM is the development branch, dev_dtp360 is the same branch with one line of code change -- forcing nsphys=1 (so for kdt>1, dtp=360, dtf=180), and exp3_dtp360 moves the temperature update from radiation out of idea_phys into gbphys/dcyc2/moninedmf while also forcing nsphys=1. It's important to note that the bug where EXP3 would incorrectly use GFS radiation in place of the blended GFS/IDEA radiation for nn=2 is fixed because nsphys=1!
![vprof_t_l150_tritprof](https://user-images.githubusercontent.com/1724113/47672529-a8461300-db88-11e8-9e81-53109a00a1b5.gif)

What we see is that most of the tropospheric improvement from the EXP3/ras2/radx family of solutions is simply the result of applying the radiation temperature update with the correct physics timestep. This was a really remarkable and unexpected result for me. It's worth emphasizing that the ~1% tropospheric warm bias is still a ~0.5% cold bias after.

It's also worth noting that this mostly fixes the rampant heating in the thermosphere as seen in the existing EXP3/ras2/radx solutions... compare (arr is a stand-in for EXP3/ras2/radx here):
![vprof_t_l150_ras2](https://user-images.githubusercontent.com/1724113/47673124-21923580-db8a-11e8-91d4-fcabc675d277.gif)
![vprof_t_l150_triglot](https://user-images.githubusercontent.com/1724113/47673134-2951da00-db8a-11e8-9fdc-c701d328796e.gif)

There are still differences, though, so there's maybe some re-tuning of the WAM physics that needs to be done before we put this issue to bed.

Couple things to consider:
1. Method for addressing this issue? (just let nsphys=1? we do not know why physics uses two timesteps, I believe Valery is looking into this with Moorthi. forcing idea_phys into the `nn` loop causes model instability after 20 hours, but using the proper 360s timestep was stable for 30 days)
2. How much re-tuning work needs to be done?

**Comment by akubaryk** [comment]
WSM is the development branch MODE=standaloneGSM (lsidea=.false., L64, ntrac=5). For the following figure, it is the baseline comparison (x=0) for the lower 45 layers, with devWAM (MODE=standaloneWAM) being the baseline comparison (x=0) for the upper 105 model layers.

WSM_dtp360 & dev_dtp360 show the impact of setting nsphys=1 with respect to standaloneGSM and standaloneWAM respectively.

![vprof_t_l64_quad](https://user-images.githubusercontent.com/31134616/47683527-37adef00-dba6-11e8-9a2b-219f247446e1.gif)

These were all run from initial conditions provided by Svetlana, with a chgres to L64 applied for the WSM runs.

We've decided to open a pull request for the one-line `nsphys=1` fix and open further issues as the need arises out of that PR.
