### ISSUE TITLE
Minor Transport Corrections

### ISSUE THREAD

**Issue by joeschoonover** [SWPC-IPE/WAM-IPE#255]
From our meeting on 11/6/2018, there were a few requests for changes in the Cross_Flux_Tube_Transport routine :

- [x] Adiabatic compression is not applied for lp < 17. However, 17 should not be hard-coded. Add a private parameter in IPE_Plasma_Class and replace the hard-coded "17"

- [x] Below 15km altitude, transport is not conducted. This altitude is hard-coded. Add a private parameter in IPE_Plasma_Class and replace the hard-coded 15km limit.

- [ ] Zonal advection should have division by "r*sin( colat_90km(lp) )".
- [ ] Add electron temperature to the pole value calculation and to the transport scheme.
- [ ] Only advect the first four ion species

**Comment by joeschoonover** [comment]
## Zonal Advection Modification Problem
When modifying the zonal advection so that
```
phi_t0   = grid % magnetic_longitude(mp) - v_ExB(1,lp,mp)*time_step/(r*sin( colat_90km(lp) ) )
```
The model stops in the `Cross_Flux_Tube_Transport` routine because the point information is advected from is outside some of the MPI ranks' mp-zone ( including halo cells). In the most severe case, the advective distance ( `v_ExB(1,lp,mp)*time_step/(r*sin( colat_90km(lp) )` ) occurs in high latitudes and is 0.18 radians ( ~10 degrees ). With grid spacing of 4 degrees, either the time step needs to be reduced by at least a factor of 3 (for transport) or the halo size increased by a factor of 3

## Thoughts on resolution
Reducing the time step for the transport only would require adding a substep time loop and that the halo update be done "just in time" for the transport scheme. This would be the more optimal choice for maintaining accuracy - although, in theory, Semi-Lagrangian schemes are stable for larger CFL numbers, the accuracy of the advection is reduced with larger CFL number. This would harm scaling efficiency; however, since FLIP still dominates run time, it may not be significant.

**Comment by akubaryk** [comment]
Any update on this one @gmillward @twfang?

**Comment by gmillward** [comment]
Yeh, that is sorted, in that the code calculates a sub-timestep for transport and uses that.  It still remains to be seen whether it works for real stormtime conditions.

**Comment by akubaryk** [comment]
Can open a new storm-time-specific issue if it's a problem, then. Thanks!
