### ISSUE TITLE
Tropospheric Radiation Difference in WAM vs GSM

### ISSUE THREAD

**Issue by akubaryk** [SWPC-IPE/WAM-IPE#256]
As it turns out, even after the application of #253, there's some difference in the tropospheric radiation that results in a still-significant bias.
![vprof_t_l64_quad](https://user-images.githubusercontent.com/31134616/48738297-cb0a9b00-ec0d-11e8-9991-730d5e76391f.gif)

While the global mean temperature departure is in the neighborhood of half a percent after some integration, the global mean GFS radiation departure (latitudinally-weighted) is not so clear, shown here for the first timestep (sidestepping any issues with model integration, physics timestep, etc.)
![global_rad](https://user-images.githubusercontent.com/31134616/48739988-f774e600-ec12-11e8-9ded-bff72e6964b0.png)

Additionally, the 2D imagery shows significant regional departures. This following animation shows the raw differences between WAM and "WSM" (lsidea=.false., levs=64, levr=64, ntrac=5) for the lower 45 layers with increasing height (identical height definitions for WAM and WSM).
![exp3_wsm_raw_diff2](https://user-images.githubusercontent.com/31134616/48740431-b1208680-ec14-11e8-9bf4-db91c9f3ed8f.gif)

What is shown is the untouched GFS radiation (hlw+swh*xmu) at kdt=1, meaning there is no difference in the initial conditions, no influence of the model physics, and no difference caused by the physics timestep. The raw differences are difficult for visualization purposes because the typical temperature tendencies from radiation are orders of magnitude smaller than these maximal differences. This is the percent difference:
![exp3_wsm_diff](https://user-images.githubusercontent.com/31134616/48738484-6439b180-ec0e-11e8-943e-a5dc9f7685ea.gif)

It's messy due to the near-zero values, but the broad pattern is evident. Just to demonstrate the effect, setting levr=64 for WAM results in the following figure:
![levr64-wsm_diff](https://user-images.githubusercontent.com/31134616/48738517-829fad00-ec0e-11e8-98ec-c21d74c00b4d.gif)

We see notably less severe departures across the lowest 40 layers or so, but some diurnal signature is evident toward the top of the comparison domain. GFS radiation treats all layers above levr as a single layer, and it's clear that this has some effect beyond layers 40.

We would ideally seek identical radiation between the two at this first timestep: levr=90 for WAM and levr=64 for WSM have the same physical top, roughly 60km, and the impact of the "layer 91" in WAM should not be so severe. We will likely need to deeply inspect the radiation routines or request assistance from people with relevant knowledge to determine what the exact issue is and if a viable solution exists.

**Comment by akubaryk** [comment]
Adiabatic WAM-GSM w/ 5 tracers is proving to be problematic. In the GSM dynamical core, there's an option for Rayleigh damping that is enabled only for adiabatic runs -- I added that to the lsidea=.true. dynamical core -- but it still results in the model failing after approximately 92 hours of integration. Some comparisons have been made with adiabatic L149 FV3, and they are not favorable. The investigation continues.

**Comment by joeschoonover** [comment]
Resolved by PR #269
