### ISSUE TITLE
Fortran files under NEMS may not need to be tracked

### ISSUE THREAD

**Issue by joeschoonover** [SWPC-IPE/WAM-IPE#26]
Underneath the NEMS directory, only a select set of Fortran code is needed to be tracked in the repository. Additional files, I think with .f90 and .F90 extensions, are generated after pre-processing. These can be removed from the repository.

**Comment by akubaryk** [comment]
This is likely related to #13.

**Comment by akubaryk** [comment]
Closed with #13.
