### ISSUE TITLE
quantify the impacts of the compilers changing on WAM physics  

### ISSUE THREAD

**Issue by ZhuxiaoLi66** [SWPC-IPE/WAM-IPE#264]
The IPE-refactor version of WAM-IPE applies several newer version compilers compared with the development tip WAM version. Preliminary validations show that the changing of compilers impact the WAM physics at a not_that_much degree, while the further investigation is needed for quantifying the influences.     

a) An annual WAM run by develop_dip_code+IPE_refactor_compilers is running now and will be validated against the annual run of development dip version with the current configuration setting.  
b) Case study, diurnal and seasonal variation features will be checked and validated. 
c) global mean, 2D and zonal mean of temperature and compositions will be compared to quantify the impacts on the WAM physics.

**Comment by ZhuxiaoLi66** [comment]
git fetch
git checkout origin/ipe_refactor -- modulefiles/theia
git checkout origin/ipe_refactor -- conf/
NEMS/NEMSAppBuilder rebuild app=standaloneGSM

**Comment by ZhuxiaoLi66** [comment]
![T_wind_2D_WAM_MSIS_F120_Kp3_135lev_201304_nsphys1_tip_compiler.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46dcab8d2a8c8796ddcd80748570cfb91a6f144c0f55f17b4faef37b80132854030a08c343585e47fcfde675e5f66439c95d64a9882d3027996051f5e4d75dad1da860c910dfe3efce5ecafa3877e78e87496b4f501edfad5e61a0994a9b0da24be64b5db60f2421b72862231acd54206e796d34aaf4d557828169adb814265ecceae2f3045f.png)
![T_wind_2D_WAM_MSIS_F120_Kp3_135lev_201307_nsphys1_tip_compiler.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46dcab8d2a8c8796ddcd80748570cfb91a6f144c0f55f17b4faef37b80132854030a08c343585e47fcfee675e5f66439c95d64a9882d3027996051f5e4d75dad1da860c910dfe3efce5ecafa3877e78e87496b4f501edfad5e61a0994a9b0da24be64b5db60f2421b72862231acd54206e796d34aaf4d557828169adb814265ecceae3fb045f.png)
![T_wind_2D_WAM_MSIS_F120_Kp3_135lev_201310_nsphys1_tip_compiler.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46dcab8d2a8c8796ddcd80748570cfb91a6f144c0f55f17b4faef37b80132854030a08c343585e47fdf9e675e5f66439c95d64a9882d3027996051f5e4d75dad1da860c910dfe3efce5ecafa3877e78e87496b4f501edfad5e61a0994a9b0da24be64b5db60f2421b72862231acd54206e796d34a9fdd557828169adb814265ecceae3fa045f.png)
![T_wind_2D_WAM_MSIS_F120_Kp3_135lev_201401_nsphys1_tip_compiler.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46dcab8d2a8c8796ddcd80748570cfb91a6f144c0f55f17b4faef37b80132854030a08c343585e40fcf8e675e5f66439c95d64a9882d3027996051f5e4d75dad1da860c910dfe3efce5ecafa3877e78e87496b4f501edfad5e61a0994a9b0da24be64b5db60f2421b72862231acd54206e796d34aaf4d557828169adb814265ecceaedfb045f.png)

**Comment by ZhuxiaoLi66** [comment]
![O_to_N2_0UT_WAM_MSIS_F120_Kp3_135lev_201304_nsphys1_compiler.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46c7ab8e2cbdadfbb0b98a779b6ad1b9166b145a1a3b857a22d5dc03af1144505c5a12f907375d44fdfa892fc9e87f30d21548ecbe3e002986644df9fa9003ad41f87fd11ad6f2ae805ec5ba3d20ef8dda1e6b18534a8aab5d35a1ca1e9c58f14de95f49b651673db2296b250dc15c672679662ea1fdda528e8c62a1ba16295fc1e4f6b7.png)
![O_to_N2_0UT_WAM_MSIS_F120_Kp3_135lev_201307_nsphys1_compiler.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46c7ab8e2cbdadfbb0b98a779b6ad1b9166b145a1a3b857a22d5dc03af1144505c5a12f907375d44fdfa892cc9e87f30d21548ecbe3e002986644df9fa9003ad41f87fd11ad6f2ae805ec5ba3d20ef8dda1e6b18534a8aab5d35a1ca1e9c58f14de95f49b651673db2296b250dc15c6726796621a1fdda528e8c62a1ba16295fc1e5f6b7.png)
![O_to_N2_0UT_WAM_MSIS_F120_Kp3_135lev_201310_nsphys1_compiler.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46c7ab8e2cbdadfbb0b98a779b6ad1b9166b145a1a3b857a22d5dc03af1144505c5a12f907375d44fdfa882bc9e87f30d21548ecbe3e002986644df9fa9003ad41f87fd11ad6f2ae805ec5ba3d20ef8dda1e6b18534a8aab5d35a1ca1e9c58f14de95f49b651673db2296b250dc15c6726796527a1fdda528e8c62a1ba16295fc1e4f6b7.png)
![O_to_N2_0UT_WAM_MSIS_F120_Kp3_135lev_201401_nsphys1_compiler.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46c7ab8e2cbdadfbb0b98a779b6ad1b9166b145a1a3b857a22d5dc03af1144505c5a12f907375d44fdfd892ac9e87f30d21548ecbe3e002986644df9fa9003ad41f87fd11ad6f2ae805ec5ba3d20ef8dda1e6b18534a8aab5d35a1ca1e9c58f14de95f49b651673db2296b250dc15c672679662ea1fdda528e8c62a1ba16295fc1e4f6b7.png)

**Comment by ZhuxiaoLi66** [comment]
![monthly_zonal_mean_T_WAM_MSIS_F107_120_201304_nsphys1_compiler_5p.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46e59b94378a8fb0b0f3b04da551cf992c47294c1d3b940a5dbace1b967144275e5f49c3405a5f2bfef98828a6b2532ec91c53a4926c3027996051f5e4d75dd004fa32975dc5f4e3d01993ac2f2ff58edd4f3b16034dd8aa5b63f29a1fc858f718b41955a3153e71fa64742d19c0412875213264b9f6cd57808f61a1be192654cde2e6fa1f15a06e95.png)
![monthly_zonal_mean_T_WAM_MSIS_F107_120_201307_nsphys1_compiler_5p.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46e59b94378a8fb0b0f3b04da551cf992c47294c1d3b940a5dbace1b967144275e5f49c3405a5f2bfef98828a6b1532ec91c53a4926c3027996051f5e4d75dd004fa32975dc5f4e3d01993ac2f2ff58edd4f3b16034dd8aa5b63f29a1fc858f718b41955a3153e71fa64742d19c0412875213264b9f6cd57808f61a1be192654cde2e6fa1f15a56e95.png)
![monthly_zonal_mean_T_WAM_MSIS_F107_120_201310_nsphys1_compiler_5p.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46e59b94378a8fb0b0f3b04da551cf992c47294c1d3b940a5dbace1b967144275e5f49c3405a5f2bfef98828a7b6532ec91c53a4926c3027996051f5e4d75dd004fa32975dc5f4e3d01993ac2f2ff58edd4f3b16034dd8aa5b63f29a1fc858f718b41955a3153e71fa64742d19c0412875213264b9f6cd54868f61a1be192654cde2e6fa1f15a26e95.png)
![monthly_zonal_mean_T_WAM_MSIS_F107_120_201401_nsphys1_compiler_5p.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46e59b94378a8fb0b0f3b04da551cf992c47294c1d3b940a5dbace1b967144275e5f49c3405a5f2bfef9882fa6b7532ec91c53a4926c3027996051f5e4d75dd004fa32975dc5f4e3d01993ac2f2ff58edd4f3b16034dd8aa5b63f29a1fc858f718b41955a3153e71fa64742d19c0412875213264b9f6cd578f8f61a1be192654cde2e6fa1f15a36e95.png)

**Comment by ZhuxiaoLi66** [comment]
The following is the validation of the new compiler&configration based on JDEL8 (tip) version.

**Comment by ZhuxiaoLi66** [comment]
![T_wind_2D_WAM_jdel8_MSIS_2013_1_ref_ori_compiler_5p.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46dcab8d2a8c8796ddcd80748570cf9e2d432b2b1629900243bab178ee114450301d1bfa2e071d1d93aad676e6ef6025c8330eadc3714d3484624bf9ebc60db513bf728b4a8db0e9db19c6be6f26b38b8f4e6d4b51188ef95527bc8b099906a214bc141ff1512469f477317646911b752d6d6222a8f4d6508e972d.png)
![T_wind_2D_WAM_jdel8_MSIS_2013_4_ref_ori_compiler_5p.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46dcab8d2a8c8796ddcd80748570cf9e2d432b2b1629900243bab178ee114455301d1bfa2e071d1d93aad676e6ef6025c8330eadc3714d3484624bf9ebc60db513bf728b4a8db0e9db19c6be6f26b38b8f4e6d4b51188ef95527bc8b099906a214bc141ff1512469f477317646911b752d6d6222a8f4d65080972d.png)
![T_wind_2D_WAM_jdel8_MSIS_2013_7_ref_ori_compiler_5p.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46dcab8d2a8c8796ddcd80748570cf9e2d432b2b1629900243bab178ee114456301d1bfa2e071d1d93aad676e6ef6025c8330eadc3714d3484624bf9ebc60db513bf728b4a8db0e9db19c6be6f26b38b8f4e6d4b51188ef95527bc8b099906a214bc141ff1512469f477317646911b752d6d6222a8f4d65481972d.png)
![T_wind_2D_WAM_jdel8_MSIS_2013_10_ref_ori_compiler_5p.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46dcab8d2a8c8796ddcd80748570cf9e2d432b2b1629900243bab178ee1144505f300cf917370006a596da74fbf6652cdf1e64e8917f4366867f4ef6edd15bad0ba825d94f80bebadf1d95ee6b77e4df8f4f3f4d504c89f85b3db285598a09a81fbe100cee467471ec64377b4d951b702c6a6123afffd75f858672e9.png)

**Comment by ZhuxiaoLi66** [comment]
![monthly_zonal_mean_T_WAM_jdel8_MSIS_2013_1_ref_ori_compiler_5p.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46e59b94378a8fb0b0f3b04da551cf992c47294c1d3b940a5dbae92cba4e233e223c37cf2e5a5f45ff968844e4e36a1fd51e5282823202349f6144eed7875fad1da860c910dfe3efce5ecafa3877e78e87496b4f501edfad5e61a0994a9b0da24be64b5db60f2421b72862231acd54206e796d34aaf5d557828060a5bc152b5fc0e7e1fc045f.png)
![monthly_zonal_mean_T_WAM_jdel8_MSIS_2013_4_ref_ori_compiler_5p.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46e59b94378a8fb0b0f3b04da551cf992c47294c1d3b940a5dbae92cba4e233e223c37cf2e5a5f45ff968d44e4e36a1fd51e5282823202349f6144eed7875fad1da860c910dfe3efce5ecafa3877e78e87496b4f501edfad5e61a0994a9b0da24be64b5db60f2421b72862231acd54206e796d34aafbd557828060a5bc152b5fc0e0edf2045f.png)
![monthly_zonal_mean_T_WAM_jdel8_MSIS_2013_7_ref_ori_compiler_5p.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46e59b94378a8fb0b0f3b04da551cf992c47294c1d3b940a5dbae92cba4e233e223c37cf2e5a5f45ff968e44e4e36a1fd51e5282823202349f6144eed7875fad1da860c910dfe3efce5ecafa3877e78e87496b4f501edfad5e61a0994a9b0da24be64b5db60f2421b72862231acd54206e796d34aaf5d557828060a5bc152b5fc0e5e2fc045f.png)
![monthly_zonal_mean_T_WAM_jdel8_MSIS_2013_10_ref_ori_compiler_5p.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46e59b94378a8fb0b0f3b04da551cf992c47294c1d3b940a5dbae92cba4e233e223c37cf2e5a5f45ff96882bc9f46926e50349b4be3e002986644df9faed1aff13a632cb0ddaece9d908d2e22f20b58b8a47384b544d8fa90f36f4994bc90ba31fe14a53ac012a71a427682818c9473f7929752cb9fdd85c868065a4bb162a52c1ebe2fd1600ec.png)

**Comment by ZhuxiaoLi66** [comment]
![monthly_zonal_mean_MMS_WAM_jdel8_MSIS_2013_1_ref_ori_compiler_5p.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46e59b94378a8fb0b0f3b04da551cf992c47294c0429901447a4ce17b5467e0d573033cf383b3046fcf88a44a7d97e25dc3354af88020c2b9b7d48f0edc070ba41a83c990fc7e9e6df1f84fa3737e2d98f4a36185049dcf90b67a3cd4bc859a51eb54d52a21b247ff434672213cb432c663e2534a1eede518d8465a1ba112953cde1edfe1213b331.png)
![monthly_zonal_mean_MMS_WAM_jdel8_MSIS_2013_4_ref_ori_compiler_5p.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46e59b94378a8fb0b0f3b04da551cf992c47294c0429901447a4ce17b5467e0d573033cf383b3046fcf88a44a2d97e25dc3354af88020c2b9b7d48f0edc070ba41a83c990fc7e9e6df1f84fa3737e2d98f4a36185049dcf90b67a3cd4bc859a51eb54d52a21b247ff434672213cb432c663e2534a1eede518d8465a1ba112953cde1edfe1615b331.png)
![monthly_zonal_mean_MMS_WAM_jdel8_MSIS_2013_7_ref_ori_compiler_5p.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46e59b94378a8fb0b0f3b04da551cf992c47294c0429901447a4ce17b5467e0d573033cf383b3046fcf88a44a1d97e25dc3354af88020c2b9b7d48f0edc070ba41a83c990fc7e9e6df1f84fa3737e2d98f4a36185049dcf90b67a3cd4bc859a51eb54d52a21b247ff434672213cb432c663e2534a1eede5f8d8465a1ba112953cde1edfe1717b331.png)
![monthly_zonal_mean_MMS_WAM_jdel8_MSIS_2013_10_ref_ori_compiler_5p.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46e59b94378a8fb0b0f3b04da551cf992c47294c0429901447a4ce17b5467e0d573033cf383b3046fcf88a44a7b65332df0a64b293343027996051f5e4d75dd004fa32975dc5f4e3d01993ac2f2ff58edd4f3b16034dd8aa5b63f29a1fc858f718b41955a3153e71fa64742d19c0412875213264b9f6cd57808f61a1bf102e50cde6e6f31210a16e95.png)

**Comment by ZhuxiaoLi66** [comment]
https://github.com/SWPC-IPE/WAM-IPE/commit/2f516e2a75600f5dde89fc89ee3af877e4d4c27c

FFLAGS      = $(TRAPS) $(FINCS) -openmp -convert big_endian -assume byterecl -fp-model precise -diag-disable 8290,8291
FFLAGS      = $(TRAPS) $(FINCS) -qopenmp -convert big_endian -assume byterecl -fp-model precise -diag-disable 8290,8291

module load intel impi/5.1.1.109 netcdf
module load intel/16.1.150 impi/5.1.1.109 netcdf esmf/7.1.0r

**Comment by ZhuxiaoLi66** [comment]
![T_wind_2D_WAM_jdel8_MSIS_fix_135lev_20130301_refactor_ori_compiler_24hrs.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46dcab8d2a8c8796ddcd80748570cf9e2d432b2b1629900243bae521a77d2a525a031bea2e5a5f45fff98a2ba7d97e25dc0d58a98e2f302b84647effe7df5fe65def62e44d81eefec95edcfa7d67b8d1da1c7a0c0f0a8cad5d30a89f1e990df01db34e01a4133730b322367b419c0c693e293678ffa3820fcdd022b6b0022e5ec2e2e1ff1716a77cdec70c79655149e7.png)

**Comment by ZhuxiaoLi66** [comment]
![T_wind_2D_WAM_jdel8_MSIS_fix_135lev_20130301_refactor_ori_compiler_0_5UT.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46dcab8d2a8c8796ddcd80748570cf9e2d432b2b1629900243bae521a77d2a525a031bea2e5a5f45fff98a2ba7d97e25dc0d58a98e2f302b84647effe7df5fe65def62e44feab3d9ee5edcfa7d67b8d1da1c7a0c0f0a8cad5d30a89f1e990df01db34e01a4133730b322367b419c0c693e293678ffa3820fcdd022b6b0022e5ec2e2e1ff1716a77cdfc20f73615549e7.png)

**Comment by akubaryk** [comment]
What height are those 2D plots from?

**Comment by ZhuxiaoLi66** [comment]
about 250km, WAM Lev135.

**Comment by ZhuxiaoLi66** [comment]
Evolution of the disparity of the WAM simulated Temp. (at about 250km) with the two different configuration  ( IPE-refactor - original).

![T_wind_2D_WAM_jdel8_MSIS_fix_135lev_20130301_refactor_ori_compiler_168HR.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46dcab8d2a8c8796ddcd80748570cf9e2d432b2b1629900243bae521a77d2a525a031bea2e5a5f45fff98a2ba7d97e25dc0d58a98e2f302b84647effe7df5fe65def62e44e83bec4e85edcfa7d67b8d1da1c7a0c0f0a8cad5d30a89f1e990df01db34e01a4133730b322367b419c0c693e293678ffa3820fcdd022b6b0022e51c2e2e1ff1715a37adbc50e706a5249e7.png)

**Comment by ZhuxiaoLi66** [comment]
It seems the development of the difference in Temp. stopped in the third simulation month. The maximum spot at each time in this month is around 100 to 150 degree.

**Comment by ZhuxiaoLi66** [comment]
Here you go!  the corresponding spot at lower altitude which is corresponding to the first wave at 250km has been found at Lev51! 

![T_wind_2D_WAM_jdel8_fix_50lev_20130301_refactor_ori_compiler_0_5UT_cb.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46dcab8d2a8c8796ddcd80748570cf9e2d432b2b1602aa334fd0b324ba5444535f5e4dac42585e2bbeacdf7af5f26332e50349b4be3e002986644df9faed1fd004df44e41cd7a4a0980c82b76770b4cf9d452c1b57188cf75b60f1cc4d9e0af51fe14d54f7466263e1703e6e5b865c24723f387bf2b68a14958f72a5b21a2e53cde2ecfa1115a17bdec000632e.png)

**Comment by joeschoonover** [comment]
@ZhuxiaoLi66 can you calculate RMS of the temperature difference at each time. The goal is to get a time-series to look at to see if disturbances are actually plateauing

**Comment by akubaryk** [comment]
These are videos that start from the surface and increase in model level height. The top frame is the difference between the same compiler (development branch intel/14.0.2) running with 16 and 32 processors, and the bottom frame is the difference between two different compilers (`development` intel/14.0.2 and `ipe_refactor` intel/16.1.150) both using 32 CPUs. I am differencing the mean gridcell temperature field as recorded by the physics routines.

[first timestep](https://drive.google.com/open?id=1ZqLe2Nn6dmzVF_F0NXsQ4vamafQg_bIl)
[second timestep](https://drive.google.com/open?id=1uAfsCqUsKdN8QTBVIVR7SPTMkHIiK7on)
[third timestep](https://drive.google.com/open?id=1kkecAg1uyakgAtAsOhZImMhjxUFJ-49D)
[fourth timestep](https://drive.google.com/open?id=1durdR2iVny-vw4I-s1VRQMwyW4cfMXTR)

The videos can be a bit hard to visually process at first glance, so here's a basic rundown of what I see.

**First timestep**
Top frame: some random single-point departures in the upper model levels
Bottom frame: no differences.

**Second timestep**
Top frame: incoherent-with-height point differences throughout the entire domain, as well as entire single latitudinal bands that exhibit a constant difference.
Bottom frame: no differences.

**Third timestep**
Top frame: Few "major" (0.003K) vertically coherent departures visible for the first time.
Bottom frame: like the top frame of the second timestep.

**Fourth timestep**
Top frame: like the top frame of the third timestep, more severe departures (0.01K) and more frequent.
Bottom frame: like the top frame of the third timestep, less severe departures (0.001K).

The point that I want to make here is that the compiler change is less of an issue by this metric than changing the number of cores that the model integrates with. It is a fact of the GSM that minor changes to computational configuration will cause a butterfly departure from a control run when using compiler optimizations. It is still true that we can't blame one particular configuration for being "right" or "wrong" -- only that they are different.

**Comment by ZhuxiaoLi66** [comment]
@akubaryk good job!

**Comment by ZhuxiaoLi66** [comment]
The following investigation results for the runs with the two different configurations support Adam's above point.  They are the further looks on the first 4 time steps output of Temp. at model level of 1, 2, 50 and 135 of the two runs. we checked the changes for the same run after each time step, also the difference between the two runs at each the same time step. 
The conclusion is that the tendencies of the change after each time step (model's performance) are very consistent between the two runs and only a tiny random difference between the two runs exist compared with the magnitude of their time change tendencies at that time step.
Please notice the step0 data means the IC file of that run, step1 output is the sigf00 file after one dycore step, the field with value 0 doesn't mean the two compared files are bit by bit identical.

**Comment by ZhuxiaoLi66** [comment]
![T_2D_WAM_jdel8_fix_LEV1_refactor_ori_compiler_20130301_tsp_0.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46dcabc807bdb488a2d6b547a151a8ab2f4f3f4c0521957a4f97e62ebe416f0e1d3011ee18370c1ba1b9d077f3f453728a5d08edd26d5e1b827e51c3b89003ad41f87fd11ad6f2ae805ec5ba3d20ef8dda1e6b18534a8aab5d35a1ca1e9c58f14de95f49b651673db2296b250dc15c672679662ea1fdda53858566acbd112d53c8e7f6b7.png)
![DT_2D_WAM_jdel8_fix_LEV1_refactor_ori_compiler_20130301_tsp_same.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46cca0a571a6bc9eaec48049a058fccc16402e6b1628861d21baf12db9437815001d21f303013017a3a4c972fae37e1f885c0aeed16e5f75a97952ecd7c14ee254a83c990fc7e9e6df1f84fa3737e2d98f4a36185049dcf90b67a3cd4bc859a51eb54d52a21b247ff434672213cb432c663e2534a1eede5f8d8465a1b810295ecfe0e0fa1316b331.png)

**Comment by ZhuxiaoLi66** [comment]
![T_2D_WAM_jdel8_fix_LEV2_refactor_ori_compiler_20130301_tsp_0.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46dcabc807bdb488a2d6b547a151a8ab2f4f3f4c052195794f97e62ebe416f0e1d3011ee18370c1ba1b9d077f3f453728a5d08edd26d5e1b827e51c3b89003ad41f87fd11ad6f2ae805ec5ba3d20ef8dda1e6b18534a8aab5d35a1ca1e9c58f14de95f49b651673db2296b250dc15c672679662ea1fdda53858566acbd192f52cfe1f6b7.png)
![DT_2D_WAM_jdel8_fix_LEV2_refactor_ori_compiler_20130301_tsp_same.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46cca0a571a6bc9eaec48049a058fccc16402e6b1628861d22baf12db9437815001d21f303013017a3a4c972fae37e1f885c0aeed16e5f75a97952ecd7c14ee254a83c990fc7e9e6df1f84fa3737e2d98f4a36185049dcf90b67a3cd4bc859a51eb54d52a21b247ff434672213cb432c663e2534a1eede5f8d8465a1b810295ec0e3e7fb1016b331.png)

**Comment by ZhuxiaoLi66** [comment]
![T_2D_WAM_jdel8_fix_LEV50_refactor_ori_compiler_20130301_tsp_0.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46dcabc807bdb488a2d6b547a151a8ab2f4f3f4c0521957e20baf12db9437815001d21f303013017a3a4c972fae37e1f885c0aeed16e5f75a97952ecd7820da313fa62d415d0e5f89846d2ed6f25e283891a6f4b034edbfc0935a098189d0cf64ce74547b8017432b82269211ede4b373e617527acf6de53828760a2b2182c5ecce2ece85b.png)
![DT_2D_WAM_jdel8_fix_LEV50_refactor_ori_compiler_20130301_tsp_same_2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46cca0a571a6bc9eaec48049a058fccc16402e6b1628861d25d5dc3aba447a021b000cc31e1a062bafa6d46bffea6932e55e0becd26d5c74c75255eff8ed5cee5cef4f895d99a4fcc8139abd6e61f5819d4a6c1e00108faa0c60a6cf19cb0cf64be01e00f0133165ee642a6e05c5402173363e6cfebecd5c958469aebb152a54c8e5ecf21e15a07adcd544.png)

**Comment by ZhuxiaoLi66** [comment]
![T_2D_WAM_jdel8_fix_LEV135_refactor_ori_compiler_20130301_tsp_0.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46dcabc807bdb488a2d6b547a151a8ab2f4f3f4c0521957a23d0dc3aba447a021b000cc31e1a062bafa6d46bffea6932e55e0becd26d5c74c75255eff8ed1fad1da860c910dfe3efce5ecafa3877e78e87496b4f501edfad5e61a0994a9b0da24be64b5db60f2421b72862231acd54206e796d34aafbd557828062a4bc182654ceebe2f9045f.png)
![DT_2D_WAM_jdel8_fix_LEV135_refactor_ori_compiler_20130301_tsp_same_2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46cca0a571a6bc9eaec48049a058fccc16402e6b1628861d21d6b617ad477d000c1b11ee2e071d1d93aad676e6ef6025c83309edd06e5f77c63c7ee8fbc270fc50e775e44d97aaaeca0e9fb26876a399855d3b4c051d81f90864f59f1d9a5ba24be14c06f1473664e07e246055d64f2b78343a7fe1a99d448d9761acb0112a53cae3e2f21f11a97fd9cf1b3c.png)

**Comment by ZhuxiaoLi66** [comment]
The following is the RMSD of the TEMP. at LEV135 between the two compiler runs. 
The run start at 2013030100, the Temperature in the current plot is 6hrly during June-August. It indicates that the RMSD climbing time and butterfly effect from the slight difference at the very beginning is longer than expected and after 4mons finally it gets down and stabilized.
![Temp_RMSD_201306-09_compiler.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46dc919733bdb184bccd8011f40ca3c47f0b772a1607ac26608cef2dad0037431f1d11f6140b1b56f6eb8c79a6b33476df0d5eeb873f5c20c63d10ffedd61fb807b232975dc7e7e2de139db17770a599855d3f170f198cfa5f36a29d4ac85cf04fe95f18.png)

**Comment by ZhuxiaoLi66** [comment]
![T_2D_WAM_jdel8_fix_LEV1_refactor_ori_compiler_20130301_8tsp.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46dcabc807bdb488a2d6b547a151a8ab2f4f3f4c0521957a4f97e62ebe416f0e1d3011ee18370c1ba1b9d077f3f453728a5d08edd26d5e1bce7952ecaa9e0dff43e57ade1cc1a4b6984992e8382de1dede1a3848571bddff5d34f3cc1fc85ff043f35147e6426837b92b6f3612d60c7f3e6a602caaf9da54848660a3ba19285ec9f1a9.png)

**Comment by ZhuxiaoLi66** [comment]
![DT_2D_WAM_jdel8_fix_LEV1_refactor_ori_compiler_20130301_tsp_same_8p.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46cca0a571a6bc9eaec48049a058fccc16402e6b1628861d21baf12db9437815001d21f303013017a3a4c972fae37e1f885c0aeed16e5f75a97952ecd7c14ee254d528cb5d99a4fcc8139abd6e61f5819d4a6c1e00108faa0c60a6cf19cb0cf64be01e00f0133165ee642a6e05c5402173363e6cfebecd5c958467aebb152a54cbe0e7fe1f17a87aded544.png)
