### ISSUE TITLE
The comparison of temp. and composition among WAM before nsphys1, nsphys1 correction and 8th-order diffusion option during 20130317 storm

### ISSUE THREAD

**Issue by ZhuxiaoLi66** [SWPC-IPE/WAM-IPE#265]
Two issues initialized and motivated the current comparison in the related WAM physics, they are the found of nsphys related bug by Adam and the issue Tim brought up recently which is that the fine physics features of WAM before NEMS seems become indistinct in the new WAM version with NEMS.      

We would like to bring the former setting of WAM before NEMS as much as possible to represent the WAM physics more accurately.

**Comment by ZhuxiaoLi66** [comment]
![unnamed](https://user-images.githubusercontent.com/22546571/49760014-42869400-fcbb-11e8-9407-68c8ac5d7d69.png)

**Comment by ZhuxiaoLi66** [comment]
Adam already did several runs and did some videos and plotting on the output. The above figure is about the comparison between the 8th_order_diffusion(in idea_deldifs_init.f).vs.4th_order_diffusion(current) output. it is become quite different after 48 hrs running.

**Comment by ZhuxiaoLi66** [comment]
The 8th_order_diffusion version performed very well during the whole storm period and got more fine and reasonable physics structure in Temperature.

**Comment by akubaryk** [comment]
`jdel8` has been created as a branch off `static_nsphys` with another one-line change, this one in NEMS/src/atmos/gsm/dyn/idea_deldifs_init.f, changing `JDEL=4` to `JDEL=8`.

L128 (~200km) temperature for quiet time (24h from 2013031600, spinup from 2013030100):
[development](https://drive.google.com/open?id=1WKatyBdRFowZZX0Pm2lMfEh7LYWpdNcp)
[static_nsphys](https://drive.google.com/open?id=1L018t4qMzCJnA7nfQuGsRWiADhzq58qz)
[jdel8](https://drive.google.com/open?id=1aIst30WPzfghJAzaceh2x_Hg8Kb2VTXK)

Storm time (48h from 2013031700, spinup from 2013030100):
[development](https://drive.google.com/open?id=1HqDfK2oH5AXGNdPsYW-zqYYs8WAOtfyG)
[static_nsphys](https://drive.google.com/open?id=1vlDqePpKpPwgORKJ75Ek5g9_r_J8gG0c)
[jdel8](https://drive.google.com/open?id=18yXY7WQjRvEKI2yOLYvLL9ylJjG6FmW8)

`static_nsphys` expresses the expected improvement in the diurnal variability, and the 8th order diffusion expresses the expected improvement in the wavenumber 20-30 variability. `jdel8` was stable through the storm response at the standard 180s timestep.

Currently producing `static_nsphys` and `jdel8` videos for NO cooling, quiet and storm. I identified a bug in my NetCDF output code that was causing some visual artifacts in the plots coming from the physics routines; that's been rectified but the runs will take some time to redo.

**Comment by ZhuxiaoLi66** [comment]
@akubaryk thanks for the update!

**Comment by akubaryk** [comment]
**NO Cooling Level 114**

Spin-up from new 2013030100 ICs, quiet time runs 2013031600-2013031700, and storm response is from 2013031700-2013031900.

[quiet static_nsphys](https://drive.google.com/open?id=1gaM_ujx_JpOTQvJNvSW2K6P-mohXiefj)
[quiet jdel8](https://drive.google.com/open?id=1bNbiSnxXKn_1IVEiIUbyh9yhRg9QUKOR)

[storm static_nsphys](https://drive.google.com/open?id=1rhEUEZOWLQ2tT5D-Ln9ydApPb5grWke6)
[storm jdel8](https://drive.google.com/open?id=1BAx7_tilzfdDf-FBTAFxGlCUbwxiPise)

**Comment by ZhuxiaoLi66** [comment]
@akubaryk thanks for the great update!

**Comment by ZhuxiaoLi66** [comment]
So the 'quite'  runs (20130316-17) and storm response (20130317-19) are different runs for each WAM code ( static_nsphys .vs. jdel8)?

**Comment by ZhuxiaoLi66** [comment]
the 4th order horizontal diffusion seems kind of fuzzier than the 8th order one which makes sense.

**Comment by akubaryk** [comment]
They are subsets of the same 18 day run from 2013030100.

**Comment by ZhuxiaoLi66** [comment]
Got it, thanks!

**Comment by akubaryk** [comment]
**Zonal Wind Level 136**

[static_nsphys storm](https://drive.google.com/open?id=1ML8De5WUhU1B5kLSCNGIdBDKQsb-D2ZO)
[jdel8 storm](https://drive.google.com/open?id=1XGYuVnPW8gjEoeZij80TLors8lKbYOoJ)

**Comment by akubaryk** [comment]
*250km Zonal Wind*
[quiet jdel8](https://drive.google.com/open?id=1rDkwKMihPCYijGIkt1Vz5rid3yGYj3Td)

hourly output from a 2 month run w/ Kp=1.0, F10.7=70.0 is available in /scratch4/NCEPDEV/stmp3/Adam.Kubaryk/quiet_dev and /scratch4/NCEPDEV/stmp3/Adam.Kubaryk/quiet_jdel8 if anybody else would like to explore.

**Comment by akubaryk** [comment]
Sorry, for some reason it didn't enable sharing, previous link should work now.

**Comment by akubaryk** [comment]
same video as before but with bounds of 150 m/s: https://drive.google.com/open?id=10ht8C5N9-_K3T3z02vfAuvO3QLaZKkLq

**Comment by ZhuxiaoLi66** [comment]
The following is the 6hrly 2D Temp. at about 250km by before_nsphys1 WAM version
![T_wind_bef_nsphys1_WAM_LEV135_Mar18.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46dcab8d2a8c87968decb97caa4ee09c3055764c1e258e145ca0d579ec17442c0e1d4fa453444d04bea6d37ef5f22e7a985959edd4655921976817faea814bbf01bb73de1b85b1ba825edcfa7f74b9dfd0126754505a9bf54f34a8934acd5cff4fe64556a4133061e5647b.png)
![T_wind_bef_nsphys1_WAM_LEV135_Mar17.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46dcab8d2a8c87968decb97caa4ee09c3055764c1e258e145ca0d579ec17442c0e1d4fab53444d04bea6d37ef5f22e7a985959edd4655921976817faea814bbf01bb73de1b85b1ba825edcfa7f74b9dfd0126754505a9bf54f34a7934acd5cff4fe64556a4133066ef647b.png)
![T_wind_bef_nsphys1_WAM_LEV135_Mar16.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46dcab8d2a8c87968decb97caa4ee09c3055764c1e258e145ca0d579ec17442c0e1d4faa53444d04bea6d37ef5f22e7a985959edd4655921976817faea814bbf01bb73de1b85b1ba825edcfa7f74b9dfd0126754505a9bf54f34a7934acd5cff4fe64556a4133061e1647b.png)

**Comment by ZhuxiaoLi66** [comment]
The following is the 6hrly 2D Temp. at about 250km by before_nsphys1 WAM version

![T_wind_bef_nsphys1_WAM_LEV135_Mar16.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46dcab8d2a8c87968decb97caa4ee09c3055764c1e258e145ca0d579ec17442c0e1d4faa53444d04bea6d37ef5f22e7a985959edd4655921976817faea814bbf01bb73de1b85b1ba825edcfa7f74b9dfd0126754505a9bf54f34a9934acd5cff4fe64556ac1b3565e3647b.png)
![T_wind_bef_nsphys1_WAM_LEV135_Mar17.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46dcab8d2a8c87968decb97caa4ee09c3055764c1e258e145ca0d579ec17442c0e1d4fab53444d04bea6d37ef5f22e7a985959edd4655921976817faea814bbf01bb73de1b85b1ba825edcfa7f74b9dfd0126754505a9bf54f34a9934acd5cff4fe64556ac1b3566e0647b.png)
![T_wind_bef_nsphys1_WAM_LEV135_Mar18.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46dcab8d2a8c87968decb97caa4ee09c3055764c1e258e145ca0d579ec17442c0e1d4fa453444d04bea6d37ef5f22e7a985959edd4655921976817faea814bbf01bb73de1b85b1ba825edcfa7f74b9dfd0126754505a9bf54f34a7934acd5cff4fe64556ac1b3566e4647b.png)

**Comment by ZhuxiaoLi66** [comment]
Neutral Temp. during 2013031600-1900 by NSPHYS1 WAM version
![T_wind_nsphys1_tip_WAM_LEV135_Mar16.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46dcab8d2a8c879681faaf4bbd4ea1ab3d4f374c1e258e145ca0d579ec17442c0e1d4faa53444d04bea6d37ef5f22e7a985959edd4655921976817faea814bbf01bb73de1b85b1ba825edcfa7f74b9dfd0126754505a9bf54f34a7934acd5cff4fe64550a0153666ef647b.png)
![T_wind_nsphys1_tip_WAM_LEV135_Mar17.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46dcab8d2a8c879681faaf4bbd4ea1ab3d4f374c1e258e145ca0d579ec17442c0e1d4fab53444d04bea6d37ef5f22e7a985959edd4655921976817faea814bbf01bb73de1b85b1ba825edcfa7f74b9dfd0126754505a9bf54f37a2934acd5cff4fe64550a0153665e6647b.png)
![T_wind_nsphys1_tip_WAM_LEV135_Mar18.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46dcab8d2a8c879681faaf4bbd4ea1ab3d4f374c1e258e145ca0d579ec17442c0e1d4fa453444d04bea6d37ef5f22e7a985959edd4655921976817faea814bbf01bb73de1b85b1ba825edcfa7f74b9dfd0126754505a9bf54f34a8934acd5cff4fe64550a0153666ef647b.png)

**Comment by ZhuxiaoLi66** [comment]
Similar plots but by JDEL8 WAM version

![T_wind_jdel8_WAM_LEV135_Mar16.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46dcab8d2a8c879685edba4ffc62c7b504790b561f55f07e4fa8e23aee14394d4d1f0cf31b0d0c00eef39b2ef4b639788c095ab8d73b0d77923d11adebd74bbf06bc28995397f4edd4189fb5646fb2c99d452c1c071288fa593ca49e43cf5df74ce74e47e9.png)
![T_wind_jdel8_WAM_LEV135_Mar17.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46dcab8d2a8c879685edba4ffc62c7b504790b561f55f07e4fa8e23aee15394d4d1f0cf31b0d0c00eef39b2ef4b639788c095ab8d73b0d77923d11adebd74bbf06bc28995397f4edd4189fb5646fb2c99d452c1f0c1288fa593ca49e43cf5df74ce74847e9.png)
![T_wind_jdel8_WAM_LEV135_Mar18.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46dcab8d2a8c879685edba4ffc62c7b504790b561f55f07e4fa8e23aee1a394d4d1f0cf31b0d0c00eef39b2ef4b639788c095ab8d73b0d77923d11adebd74bbf06bc28995397f4edd4189fb5646fb2c99d452c1f0c1288fa593ca49e43cf5df74ce74f47e9.png)
