### ISSUE TITLE
MPI implementation of IPEToHeightGrid.f90 seg faults

### ISSUE THREAD

**Issue by joeschoonover** [SWPC-IPE/WAM-IPE#27]
Upon executing the i2hg executable with mpirun, the program issues a segmentation fault but appears to have written all of the necessary output correctly.

**Comment by akubaryk** [comment]
A few changes were made to the NetCDF file handling at the same time that I switched to the latest NetCDF library on Theia (netcdf-hdf5parallel/4.4.0) and matched intel/impi modules to match that library, so it's not clear what exactly fixed this issue... but it no longer segfaults.
