### ISSUE TITLE
Neutral Temp. check in WAM with recent update during 2013 St. Patrick storm 

### ISSUE THREAD

**Issue by ZhuxiaoLi66** [SWPC-IPE/WAM-IPE#272]
The composition (total nutral density) validation by the current updated WAM against GOCE is very encourasing, the variation and magnitude of total nutral density in WAM is very consistent with GOCE's observation along its track, except it is a little bit higher in WAM than GOCE on 20130317.    

Based on the investigation in the coinherence between netral Temp. and neureal density at 250km and 350km in WAM during storm time, their variation tendency consistent with each other very well. While since the temp. seems kind of high based on expenrince view comparied with the drivers during the storm and their is no direct Temp. observation available, the neutral temp. need get some further investigation for verification.

**Comment by akubaryk** [comment]
For reference, [250km temperature and density](https://drive.google.com/open?id=1846LfffvS6NzNz-Hr-vDTuKcS0tZaF2m) and [350km temperature and density](https://drive.google.com/open?id=1nTd8HOU-alhbEwpsQBHg9RfsAFDOR17V).

**Comment by ZhuxiaoLi66** [comment]
Adam, thanks for the update!

**Comment by ZhuxiaoLi66** [comment]
[wam_input_f107_kp.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46ff95971c8b8db99afd8045f50da7ab2256653f6b14b1247a80e03cfd1839540d5f4ba4470d0e11faafdb28f2b63c71d9095fedd66b5766da2f53fde6d640e258f075c95d8fa4be8b46c1ed392cee8989463619041e80ed10.txt)

**Comment by ZhuxiaoLi66** [comment]
Since both Tim and Mihail think it is reasonable that the higher Temp. at high levels in WAM 2013 Sr. Patrick run than CTIPe run given the large values of input drivers (Bz etc.). I would like to close the current issue.

**Comment by ZhuxiaoLi66** [comment]
Going back to the 2013 event.

4. I would be interested in checking the profiles and gradients in the region where the large temperatures >2000K or >2500K occur. As we have mentioned before the values are larger than we expected but in the region where we have strong high latitude Joule heating, so could be perfectly reasonable. Someone at the Chapman conference last week was asking where and when the large temperatures occur so he could look through his data.

5. For this 2013 event, be nice to find the locations whee the temperature exceeds say 2500K and look at the evolution of the vertical profile, and if the horizontal gradients seem reasonable smooth, i.e., not a spurious point, but a consistent profile, in an area that has a reasonable coherence.

**Comment by ZhuxiaoLi66** [comment]
Vedio of wind profile from Adam.
![max_temp_vprof.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c057e01e98f7600111319db/125516c66e82c728ace21e0d46e595821c9686a49fd6a953b652f6d665043761260ea62864c7b96aea402b5457591bfd145e0916ffad892ba7e569248a5b0de5c3714d36976345f3e5db55ea43a82a994e82bcbd8f49c1ef3f2de48a8e4937171755.gif)
