### ISSUE TITLE
Transition run scripts to SLURM

### ISSUE THREAD

**Issue by cajuncooks** [SWPC-IPE/WAM-IPE#274]
"Soon," Theia is moving from #PBS to #SBATCH (SLURM) directives for batch scheduling.

I'll need to create a new branch that uses `module load slurm` on Theia and verify that it functions identically to the current implementation. Migration suggestions have been made available by EMC [here](https://docs.google.com/spreadsheets/d/1h3PHJPZzlQsBqBNvG6gjIuuItUH4il1s-IJaXoAqSGA/edit#gid=0).

We'll also need to update any standalone post-processing scripts and the standalone IPE run scripts for the `ipe_refactor` branch. If there are any other feature branches that need the new job scheduler that *do not* want to pull from development, we also need to be made aware of that.

**Comment by akubaryk** [comment]
whoops
