### ISSUE TITLE
Convert_mpi.batch

### ISSUE THREAD

**Issue by IonospherePlasmasphereElectrodynamics** [SWPC-IPE/WAM-IPE#293]
To follow up with the PR #291, 
scripts/plot/Convert_mpi.batch, which is initiated from inside submit.sh, does not create netcdf/IPE_State.YYYYMMDDUT.nc or netcdf/plot/TEC.YYYYMMDDUT.eps (and other corresponding plots). I forgot to check this when I did the test for PR#291.

Furthermore, when I initiated Convert_mpi.batch manually, it generates the error as follows:

+ python /scratch3/NCEPDEV/stmp1/Naomi.Maruyama/tmp/issue_291/WAM-IPE/scripts/plot/../../IPELIB/scripts/plot.py --input_directory /scratch4/NCEPDEV/stmp4/Naomi.Maruyama/issue_291//netcdfAfter/ --output_directory /scratch4/NCEPDEV/stmp4/Naomi.Maruyama/issue_291//netcdfAfter//plotsAfter/
Traceback (most recent call last):
  File "/scratch3/NCEPDEV/stmp1/Naomi.Maruyama/tmp/issue_291/WAM-IPE/scripts/plot/../../IPELIB/scripts/plot.py", line 178, in <module>
    main()
  File "/scratch3/NCEPDEV/stmp1/Naomi.Maruyama/tmp/issue_291/WAM-IPE/scripts/plot/../../IPELIB/scripts/plot.py", line 137, in main
    p = Pool(num_i)
  File "/contrib/anaconda/2.3.0/lib/python2.7/multiprocessing/__init__.py", line 232, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild)
  File "/contrib/anaconda/2.3.0/lib/python2.7/multiprocessing/pool.py", line 152, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1

However, it is not clear at this moment whether these two issues are related.

**Comment by twfang** [comment]
Naomi, I have tested IPE plotting using this script with Zhuxiao last week. It seems to work well. We should review this issue together again.

**Comment by IonospherePlasmasphereElectrodynamics** [comment]
@twfang ,

Thank you very much for your checking with the issue. 
I also tested with another branch for Raffaele's PR#290(https://github.com/SWPC-IPE/WAM-IPE/pull/290). The script works with no errors, producing netcdf files and plots as expected. I do not know exactly how I got the errors I initially reported above.
I am happy to close this issue.
Thanks.
