### ISSUE TITLE
IPE refactor and WAM-IPE onto WCOSS

### ISSUE THREAD

**Issue by akubaryk** [SWPC-IPE/WAM-IPE#300]
With the completion of #297, we should be ready to merge `development` WAM with `ipe_refactor` and focus on a WCOSS transition. Careful attention will need to be paid to "overlapping" scripts, such as `NEMS/NEMSAppBuilder` and the run scripts. `ipe_refactor` branch seems to already contain the necessary code changes for running the coupled system (#288), but we need to confirm that functionality (likely need to cherry-pick the changes in `development` in the overlapping scripts since `ipe_refactor` split off) and test standalone IPE runs as well.

**Comment by gmillward** [comment]
IPE_refactor standalone now running on WCOSS phase 3. On 40 processors code running roughly 6 times faster than real-time with a 1 minute timestep and .h5 output every 30 minutes

**Comment by gmillward** [comment]
11 times faster than real-time for a 3 minute time-step, 30 minute .h5 output

**Comment by gmillward** [comment]
looks like writing an .h5 file takes about 24 seconds on WCOSS3 (40 processors).

**Comment by gmillward** [comment]
Problem with IPE on WCOSS3 traced to a missing datafile for the empirical ExB - Fixed - below is before and after:

![ipe_exb_bug_wcoss3](https://user-images.githubusercontent.com/24465054/60531367-1282fa80-9cb8-11e9-8494-d414d8c90193.png)
![ipe_running_on_wcoss3](https://user-images.githubusercontent.com/24465054/60531376-17e04500-9cb8-11e9-835d-2a8fccd45dc7.png)
