### ISSUE TITLE
Feeding in the field-line integrals from IPE into the dynamo solver

### ISSUE THREAD

**Issue by twfang** [SWPC-IPE/WAM-IPE#304]
Field-line integrals calculated from the IPE have to be rearranged into the format that dynamo solver takes. To complete this issue two action items need to be done. 

1. Make sure the field line integrals are arranged correctly. 
2. Make sure the electric field from the dynamo solver look correct.

**Comment by twfang** [comment]
The field-line integrals are now calculated and feed into the dynamo solver. The integrals look ok, but the 5th and 6th need to be double checked. 

![ipe_field_line_integrals](https://user-images.githubusercontent.com/22968399/61239347-e6299e00-a6fb-11e9-906d-df9dec611646.png)

The comparison of Ve1 and Ve1 between results from dynamo solver (top) and from the empirical model (bottom)

![comp_emp_dynamo](https://user-images.githubusercontent.com/22968399/61239414-0d806b00-a6fc-11e9-8a2b-b639f8a51394.png)

**Comment by twfang** [comment]
Results of Ve1 and Ve2 after running the standalone IPE for four hours. 

![dft_4hr](https://user-images.githubusercontent.com/22968399/61239455-2721b280-a6fc-11e9-85fe-72b55c4d06c4.png)

**Comment by gmillward** [comment]
fully parallel version (the same):
![ipe_electrodynamics_exb](https://user-images.githubusercontent.com/24465054/61241051-f0e63200-a6ff-11e9-8386-c1884c47a047.png)

**Comment by gmillward** [comment]
Equatorial vertical ExB drifts for 4 longitude sectors:

![ipe_electrodynamics_upwards_exb_drift](https://user-images.githubusercontent.com/24465054/61267949-21a58600-a757-11e9-8c83-7323052d267d.png)

**Comment by gmillward** [comment]
...and the Zonal (Eastwards) drift:
![ipe_electrodynamics_zonal_eastwards_exb_drift](https://user-images.githubusercontent.com/24465054/61310888-72969800-a7b2-11e9-9cd0-1cc4232c27e6.png)
