### ISSUE TITLE
ipe_refactor merge with development runtime failure

### ISSUE THREAD

**Issue by akubaryk** [SWPC-IPE/WAM-IPE#305]
I have a branch `ipe_refactor_development` that is now a handful of commits ahead of `ipe_refactor` -- I merged in `ipe_refactor_standalone_scripts`, and then made some changes to the build system so that WAM-IPE would compile on Theia (and should compile on WCOSS Phase 3). Then I tried to pull in `development`, which contains some of the latest changes to the IPE cap.

If you clone a fresh repository and `git checkout ipe_refactor_development` from the top directory, `git diff 4ea138e HEAD IPE/ipeCap.F90` will show the changes made in ipeCap.F90 since @rmontuoro's last commit. The rewritten cap doesn't directly use model variables from public IPE modules, instead including a wrapper which makes the IPE_Model class available via `ipe`, which further contains `ipe % grid` and `ipe % parameters` class types, several of which were used in their original form in #290. I did my best to translate any compilation errors I got into the new ipe_refactor class types, including adding the IPECAP namelist back into IPE.inp and exposing those values via `ipe % parameters`, and further changing certain grid references into `ipe % grid`.

An example RUNDIR is available here: /scratch4/NCEPDEV/stmp4/Adam.Kubaryk/dev_ipe_refactor_coupled

The end of an IPE PET file:
```
20190711 163631.412 ERROR            PET69 /home/emc.nemspara/esmf/src/Infrastructure/Mesh/src/ESMCI_Mesh_Glue.C:903 ESMCI_meshaddelements() Value unrecognized or out of range  - - there are nodes on this PET that were not used in the element connectivity list
20190711 163631.415 ERROR            PET69 /home/emc.nemspara/esmf/src/Infrastructure/Mesh/src/ESMCI_Mesh_Glue.C:1463 ESMCI_meshaddelements() Value unrecognized or out of range  - Internal subroutine call returned Error
20190711 163631.415 ERROR            PET69 ESMF_Mesh.F90:708 ESMF_MeshAddElements() Value unrecognized or out of range  - Internal subroutine call returned Error
20190711 163631.415 ERROR            PET69 ipeCap.F90:803 IPECap::InitializeRealize::IPEMe Value unrecognized or out of range  - Passing error in return code
20190711 163631.416 ERROR            PET69 ipeCap.F90:269 Value unrecognized or out of range  - Passing error in return code
20190711 163631.416 ERROR            PET69 EARTH grid component01:src/addon/NUOPC/src/NUOPC_Driver.F90:1529 Value unrecognized or out of range  - Phase 'IPDv02p3' Initialize for modelComp 3: IPM did not return ESMF_SUCCESS
20190711 163631.416 ERROR            PET69 EARTH grid component01:src/addon/NUOPC/src/NUOPC_Driver.F90:1189 Value unrecognized or out of range  - Passing error in return code
20190711 163631.416 ERROR            PET69 EARTH grid component01:src/addon/NUOPC/src/NUOPC_Driver.F90:313 Value unrecognized or out of range  - Passing error in return code
20190711 163631.416 ERROR            PET69 module_NEMS_GRID_COMP.F90:666 Value unrecognized or out of range  - Breaking out of subroutine
20190711 163631.416 ERROR            PET69 MAIN_NEMS.F90:466 Value unrecognized or out of range  - Aborting NEMS
20190711 163631.416 INFO             PET69 Finalizing ESMF
```

and the end of the stderr/stdout:
```
   Reading output file : IPE_State.apex.201303160000.h5
====== IPEMeshCreate: tile bounds ======
localPET     mps     mpe     lps     lpe
----------------------------------------
       0       1       2       1     170
       1       3       4       1     170
       2       5       6       1     170
       3       7       8       1     170
       4       9      10       1     170
       5      11      12       1     170
       6      13      14       1     170
       7      15      16       1     170
       8      17      18       1     170
       9      19      20       1     170
      10      21      22       1     170
      11      23      24       1     170
      12      25      26       1     170
      13      27      28       1     170
      14      29      30       1     170
      15      31      32       1     170
      16      33      34       1     170
      17      35      36       1     170
      18      37      38       1     170
      19      39      40       1     170
      20      41      42       1     170
      21      43      44       1     170
      22      45      46       1     170
      23      47      48       1     170
      24      49      50       1     170
      25      51      52       1     170
      26      53      54       1     170
      27      55      56       1     170
      28      57      58       1     170
      29      59      60       1     170
      30      61      62       1     170
      31      63      64       1     170
      32      65      66       1     170
      33      67      68       1     170
      34      69      70       1     170
      35      71      72       1     170
      36      73      74       1     170
      37      75      76       1     170
      38      77      78       1     170
      39      79      80       1     170
========================================
application called MPI_Abort(comm=0x84000000, 1) - process 63
[...]
```

It's worth noting that I had my branch (at e50b84f) compiling and running prior to the pull on development, but no matter what I set mesh_fill to, this branch fails. I've done as much debugging as I think I reasonably can -- if you have anything to add @rmontuoro, either with a look into the cap changes or suggestions on how to further debug, it would be greatly appreciated. One thing that I've considered is that your move to ESMF 8.0.0 was deliberate, and this isn't going to work without it, but the only ESMF that we have that works with the refactor branch is `esmf/7.1.0rp1bs03-intel18.0.1.163-impi5.1.2.150-hdf5parallel1.8.14` -- you can see it is specific to the compilers and critically the hdf5/netcdf parallel module. If that's the issue, let me know who I need to contact to get an official build with those modules, and in the meantime I can build one myself for the purposes of getting this branch prepped.

**Comment by rmontuoro** [comment]
Thank you for letting us know, @akubaryk. Will take a look.

**Comment by rmontuoro** [comment]
Both `mesh_height_min` and `mesh_height_max` are assumed to be in _meters_ internally.
Commit 14b08d2 solves this issue by converting their values from _km_ to _m_.

Compset `march2013_regression.config` runs fine with the updated WAM-IPE code, **_provided_** a larger number of PETs is assigned to the SWPC mediator (8 is too small and will generate an _out of memory_ error on Theia).

On a side note, the current version of the refactored IPE code uses a hardcoded 1-D grid decomposition along `mp`. 2D decompositions (which we used with the older IPE) may be more efficient and we should discuss this aspect further.

**Comment by akubaryk** [comment]
Great -- thank you so much for your help @rmontuoro. Do you have a recommendation for a default number of PETs for the mediator? I see from your RUNDIR that you set it to 32.

**Comment by rmontuoro** [comment]
The SWPC mediator is one of the WAM-IPE components carrying most of the workload in typical simulations, therefore it would benefit from a larger number of PETs.

The ideal number could be determined by running a few experiments to approximately determine the minimum wall clock time required for a compset and a given total number of PETs.

Note that the PETs assigned to the SWPC mediator can overlap with those assigned to other components. For instance, one possible configuration could be:

```
#############################################
####  NEMS Run-Time Configuration File  #####
#############################################

# EARTH #
EARTH_component_list: MED ATM IPM
EARTH_attributes::
  Verbosity = max
::

# MED #
MED_model:                      swpc
MED_petlist_bounds:             0 71
MED_attributes::
  Verbosity = max
  DumpFields = false
  DumpRHs = false
::

# ATM #
ATM_model:                      gsm
ATM_petlist_bounds:             0 31
ATM_attributes::
  Verbosity = max
::

# IPM #
IPM_model:                      ipe
IPM_petlist_bounds:             32 71
IPM_attributes::
  Verbosity = max
::

# Run Sequence #
runSeq::
  @60.0
    ATM -> MED :remapMethod=redist
    MED
    MED -> IPM :remapMethod=redist
    ATM
    IPM
  @
::
```

**Comment by akubaryk** [comment]
Thanks -- maybe we'll chat about this on Monday, along with the 2D decomp. Overlapping PETs makes sense to me when WAM is idle for a significant portion of a typical run. For now I'll consider this issue resolved and will update NPROCMED in the default user.config files so we can get on with testing this branch.
