### ISSUE TITLE
index for time-varying drivers needs to be implemented in IPE

### ISSUE THREAD

**Issue by twfang** [SWPC-IPE/WAM-IPE#311]
Currently, IPE only takes the first values from wam_input_f107_kp.txt file. The current_index doesn't progress with time but only set to 1. The LPI method used in IPE development branch needs to be implemented asap.

**Comment by akubaryk** [comment]
That's unexpected, will look into it right now.

**Comment by akubaryk** [comment]
8ea6f69 and e82e85c fix the issue.

**Comment by twfang** [comment]
@akubaryk , I tested the code. I do see the current_index is progressing now. But when I set timeobs in compset and print out the solar wind parameters in the code, those values still stay constant. I won't be able to work on this in a few days, but if you have any commits I will try to test it. Hope I didn't set anything wrong in my test. 

My code is under /scratch4/NCEPDEV/stmp3/Tzu-Wei.Fang/ipe_refactor_new_weimer/scripts/compsets

Outputs are located at
/scratch3/NCEPDEV/swpc/scrub/Tzu-Wei.Fang/ipe_refactor_standalone
/scratch3/NCEPDEV/swpc/noscrub/Tzu-Wei.Fang/ipe_refactor_standalone

**Comment by akubaryk** [comment]
There were a couple minor bugs in how the input parameter arrays were being setup (IPE needs the last 36 hours of data for the GetAP and GetKP functions. Additionally, the Update_Current_index call introduced in my previous commit was placed outside an nSteps do loop, causing the index to only update when an IPE output file was written. I have confirmed with the empirical E-field model that the forcing parameters are exactly what we would expect from the input file.

I have some concerns about the coupled system with respect to time tracking and will open a new issue for it.
