### ISSUE TITLE
Code crashed with INVALID MIT error

### ISSUE THREAD

**Issue by joeschoonover** [SWPC-IPE/WAM-IPE#32]
After merging with the ipe_nuopc_2d_petlayout branch, at commit 2c146c8, the WAM-IPE code crashes after 1 hour of running on both a cold start and restart, throwing the error : 
!STOP! INVALID MIT=  3  38  36  195.0000000

**Comment by akubaryk** [comment]
Confirmed with 2013031600 initial conditions, `git checkout 2c146c8b6e1bc4a95d25c8ef576d0ebba2f10e93`, fresh build, `git checkout development -- scripts`: `INVALID MIT` failure at 201303160245 using the new compset scripts.

**Comment by joeschoonover** [comment]
A cold start run for 3 hours fails at 2hr 27 min. 
Cold start run for 1 hr plus a 2 hr restart fails at 2hr 45 min

**Comment by joeschoonover** [comment]
Commit just before merging with ipe_nuopc_2d_petlayout ( 98b079d ) runs successfully past 2 hr 45 minutes

**Comment by joeschoonover** [comment]
![screenshot from 2017-09-22 10-48-10](https://user-images.githubusercontent.com/31802478/30758948-9040d198-9f91-11e7-8ad7-b6433b3e27a6.png)

This is a list of files that were modified by the merge of ipe_nuopc_2d_petlayout

**Comment by joeschoonover** [comment]
MIT=3 means that Number of points on field line is 3.
The FLIP solver complains that the equation cannot be solved by having only 3 grid points, then error stop.
The number of grid points, hence, the length of the entire field line to solve the equation is mainly determined by the electric field (EXB drift). That is why the cause of this error can be often attributed to something inside eldyn/,  or inside plasma/ in creating the imaginary flux tube for the previous time step, t=t - time_step.

**Comment by akubaryk** [comment]
@IonospherePlasmasphereElectrodynamics requested some additional debug output, the failure point is (mp,lp)=(1,139) for this 201303160000 case we've been working with.

**Comment by akubaryk** [comment]
240km, 245km, 250km T, U, V for 0003, 0006, 0009 for `98b097d`: [plots](https://drive.google.com/open?id=0B7VBbybqCsGrYmxkU1c0MTZHMmc)
Same for `2c146c8`: [plots](https://drive.google.com/open?id=0B7VBbybqCsGrMVNOTkl3UUxabFk)

Vertical profiles of V, W, T at 0006 for our problem point (blue line), the eastward adjacent point (green), and one further (red): [plots](https://drive.google.com/open?id=0B7VBbybqCsGrSVdicmE1MHJhSjg).

**Comment by joeschoonover** [comment]
Bob noted that halo cells for the grid were not updated on all mpi ranks. Raffaele found that the plasma grid was not distributed amongst all ranks and is working on a fix.

**Comment by akubaryk** [comment]
Resolved with `96c84ab`, #35 has been opened for a new issue.

**Comment by timfullerrowell** [comment]
Houjun's real-time run on WCOSS hit this same MIT error. Occurred in forecast from 03UT after the 21-03, 6 hour cycle. It crashed between 08 and 09UT, just over 5 hours into the forecast. Kp was 0, so very low. The 1 hour run starting at 08UT using real Kp ~2 also had same error. Removing WAM composition produced same error. Theia run also had same error.

**Comment by joeschoonover** [comment]
I'll open a new issue for this since MS0.6 was before the merge with 2-D domain decomposition, so the source of this particular crash is different than what we reported in this issue.
