### ISSUE TITLE
Branch Cleanup

### ISSUE THREAD

**Issue by akubaryk** [SWPC-IPE/WAM-IPE#329]
Just want to consolidate the branch discussion here.

I'd like to put something with `ipe_refactor*` into development and start axing some of the outstanding branches so we can resimplify the development workflow. `ipe_refactor_no_netcdf` is feature complete and could be pulled into `ipe_refactor_dev_wam`, but needs more testing on other systems first -- hope to do that today.

`ipe_refactor_dev_wam` is feature-consistent on the WAM and input parameter side with the tip of development *and* new_weimer (#303, #306), but does not contain the Joule Heating Integral if that is something we're going to be using in realtime runs.

We need to decide what needs to be tagged -- the current tip of development can be tagged as `old_weimer_old_ipe`; we can pull in `new_weimer` and tag that as `new_weimer_old_ipe`, and then pull `ipe_refactor_dev_wam` (with or without the no_netcdf code).

This would drop 4-5 branches from our repository while maintaining the same functionality we have now. This leaves one target branch for feature branches to pull from for updates and pull into when ready instead of the rotating option we've had for the last few weeks. Just want us all to agree on the right process.

**Comment by ZhuxiaoLi66** [comment]
I think we need to update development with new_weimer branch for WAM side at least. Maybe for Houjun's test, we need to keep new_weimer_old_ipe? don't know which version of WAM-IPE is Naomi's IPE new weimer work based on?

**Comment by akubaryk** [comment]
A tag isn't keeping a branch, it's just a string that refers to a specific commit ID -- in this case referring to the current tip of development, or the tip of development for old_weimer_old_ipe after the merge of new_weimer for new_weimer_old_ipe. I'm happy to create that tag and open the pull request to get the ball rolling on this, though. @IonospherePlasmasphereElectrodynamics is working from ipe_refactor_dev_wam (which I'd like to be development by tomorrow afternoon).

**Comment by twfang** [comment]
I agree with Adam's plan. Let's create a new_weimer_old_ipe to start with.

**Comment by ZhuxiaoLi66** [comment]
If it wouldn't cause too many CONFLICT to include the 'Joule heating integral' (merge 'new_weimer_pyonting') into ipe_refactor_wam_dev, maybe we need to do it sooner or later. Tim still want to use the integral Joule heating to scale the Joule heating calculation at intense storm time. An algorithm is going to be tested.

**Comment by akubaryk** [comment]
I'm happy to put that together tomorrow after new_weimer comes in. I may introduce a namelist variable for the logic related to the JH integral (at least for the NetCDF output...) as it isn't free to run; think it slowed down the model modestly.
