### ISSUE TITLE
issues compiling/running standalone IPE/coupled model on Phase 2

### ISSUE THREAD

**Issue by akubaryk** [SWPC-IPE/WAM-IPE#334]
`ipe_refactor_no_netcdf` is presently the branch intended for use on WCOSS Phase 2, a system comprising of Tide and Gyre.

Tide is currently the development machine. On Tide, we are obligated to compile on the compute nodes. The front-end nodes have a kernel with Spectre and Meltdown fixes that make running code compiled on the front-end nodes on the compute nodes impossible. It's unclear for now if Gyre is fine in this regard, but standalone WAM runs have been successful there when compiled on the front-end nodes, unlike Tide.

WAM-IPE in `ipe_refactor_no_netcdf` compiles on the Tide front-end nodes with the current module set. It does not compile on the compute nodes, choking at the point that ld attempts to link the compiled sources and libraries into the IPE executable, complaining that it can't find libz:

```
/usrx/local/HDF5/1.8.9/parallel/bin/h5pfc  -ffree-line-length-none -DHAVE_MPI  -L/usrx/local/HDF5/1.8.9/serial/lib -L/usrx/local/NetCDF/4.2/serial/lib  -lnetcdff  -lnetcdf  -o ipe IPE_Precision.o IPE_Constants_Dictionary.o IPE_Common_Routines.o IPE_HDF5.o IPE_Model_Parameters_Class.o IPE_Forcing_Class.o IPE_Time_Class.o IPE_Grid_Class.o IPE_MPI_Layer_Class.o IPE_Neutrals_Class.o IPE_Plasma_Class.o IPE_Electrodynamics_Class.o IPE_Model_Class.o IPE_Driver.o flip/libflip.a msise00/libmsise.a empirical_efield/libefield.a dynamo/libdynamo.a 
ifort: command line warning #10006: ignoring unknown option '-ffree-line-length-none'
ld: cannot find -lz
make[1]: *** [ipe] Error 1
make[1]: Leaving directory `/gpfs/td3/emc/global/noscrub/Adam.Kubaryk/WAM-IPE/IPELIB/src'
```

Using -show on that h5pfc command gives this:
```
mpiifort -fPIC -I/usrx/local/HDF5/1.8.9/parallel/include -reentrancy threaded -O3 -xHost -fp-model precise -L/usrx/local/HDF5/1.8.9/parallel/lib -lhdf5 -lhdf5_fortran -L/usrx/local/zlib/1.2.7-static/lib -I/usrx/local/HDF5/1.8.9/parallel/include IPE_Precision.o IPE_Constants_Dictionary.o IPE_Common_Routines.o IPE_HDF5.o IPE_Model_Parameters_Class.o IPE_Forcing_Class.o IPE_Time_Class.o IPE_Grid_Class.o IPE_MPI_Layer_Class.o IPE_Neutrals_Class.o IPE_Plasma_Class.o IPE_Electrodynamics_Class.o IPE_Model_Class.o IPE_Driver.o -ffree-line-length-none -DHAVE_MPI -L/usrx/local/HDF5/1.8.9/serial/lib -L/usrx/local/NetCDF/4.2/serial/lib -lnetcdff -lnetcdf -o ipe -L/usrx/local/HDF5/1.8.9/parallel/lib flip/libflip.a msise00/libmsise.a empirical_efield/libefield.a dynamo/libdynamo.a /usrx/local/HDF5/1.8.9/parallel/lib/libhdf5hl_fortran.a /usrx/local/HDF5/1.8.9/parallel/lib/libhdf5_hl.a /usrx/local/HDF5/1.8.9/parallel/lib/libhdf5_fortran.a /usrx/local/HDF5/1.8.9/parallel/lib/libhdf5.a -lz -lm -lgpfs -Wl,-rpath -Wl,/usrx/local/HDF5/1.8.9/parallel/lib
```
The NEMSAppBuilder continues the build because all of the IPE sources compiled correctly, allowing the cap to build and then moving on to DATAWAM, DATAIPE, and then the GSM. If running an interactive job, one can step in behind the build and do the linking process for ipe and ipe_postprocessor by hand (it turns out running the above command in IPELIB/src with the proper loaded module works fine), and allow the IPE build to finish "correctly" with ipe_build_in_place.sh, properly installing the includes and libs. Unfortunately, the compiled executable ~immediately crashes (both the coupled -- IPE crashes from within NEMS.x -- and IPE standalone). I also found that the serial IPE executable segfaults immediately, even when compiling and executing on a front-end node.

This is bizarre behavior befitting Phase 2. The "good" news is that there's a production switch to Reston happening tomorrow morning because of Hurricane Dorian, so we get to try Gyre sooner than expected.

**Comment by akubaryk** [comment]
Tide has been returned to developers because there was an issue with LSF on Luna for production purposes, unclear how much longer we'll have it before they try another prod switch.

Anyway, @gmillward recommended building IPE with --enable-debug, and that gave a very obvious issue with the serial IPE, as the HDF5 grid read was not done carefully with serial in mind. A fix has been pushed for that, and some code reversion from the grid read splitting has been done as well.

So now this is what happens:
```
[Adam.Kubaryk@t21a3 coupled_phase2_test]$ ./ipe
 
 ***********************************************
 *                                             *
 *    IPE : Initial DateTime : 201303160000    *
 *                                             *
 ***********************************************
 
Bus error (core dumped)
```

I'm assuming this is very similar to the issue that's plaguing the parallel/coupled run. Might start to introduce debug print statements since the core dump doesn't really give us a good idea of what is actually happening.

**Comment by wanghj2015** [comment]
In my case, I had some issues with ipe namelist IPE.inp and the refactored-ipe doesn't report them; e.g., in IPE_Model_Parameters_Class.F90:

        READ( UNIT = fUnit, NML = SpaceManagement, IOSTAT = iostatus )
        IF ( iostatus /= 0 ) RETURN

Don't do 'RETURN', instead print out in some meaningful way, e.g,

       !IF ( iostatus /= 0 ) RETURN
        IF ( iostatus /= 0 ) print *, ' NML = SpaceManagement iostatus = ', iostatus

and track down the errors. Once there errors cleared, wam-ipe starts running. 

BTW, there are a lot "IF ( iostatus /= 0 ) RETURN" statements in the refactored ipe, which should be done in a more meaningful or right way. See issue: https://github.com/SWPC-IPE/WAM-IPE/issues/313 too.

**Comment by akubaryk** [comment]
#313 is what introduced those return statements; it's still a work in progress as @rmontuoro noted -- just in a basic state for now.

That issue with the namelist is specific to your setup, as the IPE.inp generated by the scripts/compsets run scripts has that section. If the model is running on Gyre, then that is different from Tide and a notable result.

**Comment by wanghj2015** [comment]
Don't know these 'return' statements were introduced in https://github.com/SWPC-IPE/WAM-IPE/issues/313. Then I shouldn't have said what said about them at the teleconf.

**Comment by akubaryk** [comment]
Looking at the commit, looks like they are older than that, regardless, not relevant to this issue.

**Comment by wanghj2015** [comment]
'no-netcdf' version on 'phase2' still fail after 2 steps. Not telling where. If you/akubaryk could make it compile on 'phase3', it may be helpful too. Somehow phase3 has more info on debugging.

**Comment by wanghj2015** [comment]
1. When the 'no_netcdf' version run on phase 3 with debug mode, it caught error:

forrtl: error (73): floating divide by zero:
NEMS.x             0000000000621DD1  module_med_swpc_m        3233  module_MEDIATOR_SWPC_methods.f90
NEMS.x             0000000000616874  module_med_swpc_m        2960  module_MEDIATOR_SWPC_methods.f90

Or this line in module_MEDIATOR_SWPC_methods.F90:

            data_curr=data_prev*exp((hgt_prev-hgt_curr)/H_avg)

2. On phase 2, it won't produce such detailed info, even with debug mode turned on; just failed apparently after the first time steps:

  15: GFS ATM RUN STEP SUCCEEDED
   2: GFS ATM RUN STEP SUCCEEDED
  30:forrtl: error (78): process killed (SIGTERM)
  30:Image              PC                Routine            Line        Source 
            
  30:NEMS.x             00000000012333B5  Unknown               Unknown  Unknown

**Comment by akubaryk** [comment]
ifort's forrtl 78/SIGTERM means the process is killed by an external
source; in this case the actual failure point is the same core dump in
IPE... I expect you'd find core dump files in the RUNDIR unless those are
disabled at the user or system level. This is very likely the exact same
point of failure as Tide, so no progress on Gyre, unfortunately, and the
issue with Tide's front end/compute nodes persists -- not sure about Gyre
to that end just yet.

Traceback/debug flags do nothing in the case of a core dump, so it's normal
for there to be no additional information: Phase 3 wouldn't be any more
descriptive in failure if it was a core dump there. I've been assuming that
with serial standalone IPE we can simply gdb the core dump to get a legible
stack trace.

The divide by zero on Phase 3 could be for many reasons, but that's a
significant improvement over Phase 2 in general. We already know the basic
cause of the error (H_avg=0), and it is likely originating from the
GSM/mediator side, which we know to be extremely solid in free forecast on
Theia. Hopefully that's not too difficult to debug.

It would be great to save the log files and provide a path for additional
context if it's needed (here, to confirm that the failure in IPE occurs
before its integration begins), but I should be able to replicate these
easily.

Anyway, I'd like to keep Phase 3 in a separate issue, so I'll open a new
one for that later this morning.

**Comment by wanghj2015** [comment]
After several days, many many hours’ tests, I found that the wam-refactored-ipe can be run on phase 2 by using the following compiling options/flags for IPELIB/src/IPE_*.F90 files:

-check bounds -check stack

And here is an example of 1 hour fcst:
![image](https://user-images.githubusercontent.com/12502567/64557756-7d2b6480-d2ff-11e9-9a5d-9b01808672ab.png)

**Comment by akubaryk** [comment]
Phase 2 is being abandoned.
