### ISSUE TITLE
Consolidate IPE and IPELIB

### ISSUE THREAD

**Issue by rmontuoro** [SWPC-IPE/WAM-IPE#345]
Since IPE and IPELIB are parts of the same model component, code should be consolidated in a single (IPE) directory.

**Comment by twfang** [comment]
Should we close this?

**Comment by rmontuoro** [comment]
IPE and IPELIB are now part of a single IPE component repository: [https://github.com/SWPC-IPE/IPE](https://github.com/SWPC-IPE/IPE).
