### ISSUE TITLE
Since 10/3/17 maintenance, WAM-IPE no longer runs on Theia

### ISSUE THREAD

**Issue by akubaryk** [SWPC-IPE/WAM-IPE#36]
See example out: `/scratch3/NCEPDEV/swpc/scrub/Joseph.Schoonover/rt_91809/swpc%20130316_5day_spacewx_gsm%wam%T62_ipe%80x170/out`

Failure occurs in eldyn/get_efield90km.f...

Issue has been confirmed with MS0.6, 98b097d, and the tip of development, newly built executables and old ones.

Interestingly standalone IPE runs fine, reference: `/scratch3/NCEPDEV/swpc/save/Adam.Kubaryk/nems/WAM-IPE/WAM-IPE_dev/IPELIB/run/1507143838_ipe_theia_intel_parallel_80/standalone_output_new`

Regardless, our thinking is that the PM has caused some issue with the stack on Theia compute nodes. nemsFV3GFS is experiencing similar issues where old executables/scripts with identical module loads are now failing. Nothing intel/impi/esmf/netcdf-related has been rebuilt.

**Comment by akubaryk** [comment]
RDHPCS is rolling back Theia PM at 8pm EDT this evening.

**Comment by joeschoonover** [comment]
After the roll back, WAM-IPE runs correctly.
