### ISSUE TITLE
Need f107 file with new compset scripts

### ISSUE THREAD

**Issue by joeschoonover** [SWPC-IPE/WAM-IPE#41]
### Observed Behavior
When running the new compset scripts with user.config set to run the March 2013 initial conditions for 1 hr on theia, the job crashes  when running ./submit.sh user.config. The crash ends with a statement 'failed, no f107 file'

To resolve this issue, the file "wamp_input_f107_kp.txt" should be copied into the run directory.

### Expected Behavior
The model shouldn't crash before execution due to lack of files. 

@akubaryk

**Comment by akubaryk** [comment]
So there are a couple issues that swirl around this one. An easy fix has been applied in `ca5f7d8`, where now `checks.sh` will copy over `wam_input_f107_kp.txt` (if it exists); the exglobal script is already programmed to use that file out of the ROTDIR if it cannot find a matching .xml file, which is common for our older retrospective runs.

Ultimately we are in the process of shifting the way we handle F10.7 inputs from both the model side and the scripting side, but I think that should go under a separate "issue" if it needs one; this one can be closed.
