### ISSUE TITLE
New Feature : WAM vertical mixing to improve neutral vertical profiles

### ISSUE THREAD

**Issue by joeschoonover** [SWPC-IPE/WAM-IPE#46]
In order to improve the neutral composition, vertical mixing in WAM is going to be added. This development activity is taking place outside of the git repository. Our tasks will be :

- [x] Acquire source code with new vertical mixing
- [x] Determine any new namelist parameters and environment variables.
- [x] Update compset scripts as needed.
- [ ] Test new code, verifying the vertical mixing is fixing the issue this is meant to correct.
- [ ] Merge code into development

**Comment by joeschoonover** [comment]
From conversation with @ZhuxiaoLi0113 ,

Rashid has inserted the source code for vertical mixing with uniform vertical eddy diffusion coefficient. The code compiles and runs. Zhuxiao is currently testing WAM standalone with various diffusion coefficients to determine the "best" choice.

**Comment by joeschoonover** [comment]
I'd like to suggest that any new namelist parameters and environment variables be communicated to the development team so that we can update compset scripts accordingly. Additionally, I'd like to request an explanation of how the choice of mixing coefficient is made and documentation that backs up that choice.

**Comment by timfullerrowell** [comment]
The metric for choice of mixing coefficient is produce a reasonable match to the global mean MSIS mean molecular mass as a function of model pressure level. The current two test cases, 50 and 200 m2/s, bracket the MSIS values. There is small seasonal difference that can also be accommodated as a semi-annual variation.  Rashid and Zhuxiao are currently tuning the numbers for January and April, for selection of the coefficients and semi annual amplitude, which can be name list parameters. We can request Rashid document the algorithm and metric.

**Comment by joeschoonover** [comment]
Mean mass profile difference with MSIS. Figure created by @ZhuxiaoLi0113 
![mean_mass_diff_2_profiles_2013_amp60_wam_func-msis_new](https://user-images.githubusercontent.com/31802478/33391593-cce54620-d4f6-11e7-950c-9308dd9f3b19.png)

**Comment by ZhuxiaoLi0113** [comment]
Here is the new plot of Mean mass profiles (WAM minus MSIS) includes all 4 seasons by the new vertical_eddy_mixing code. the O/N2 ratio are largely improved at the higher levels (above 200km) compared with the output by the original code. 

![copy of mean_mass_diff_4_profiles_2013_ann_120_wam_func-msis_amp60](https://user-images.githubusercontent.com/22546571/33394407-76138560-d4ff-11e7-808d-9b560a9e140f.png)

**Comment by ZhuxiaoLi0113** [comment]
Thanks Joe for the update, I uploaded the newest plot just now.
Zhuxiao

**Comment by ZhuxiaoLi0113** [comment]
The code seems is good for now. that means maybe we don't need to do further efforts on this recently.

**Comment by joeschoonover** [comment]
Ok. should I open a pull request to merge this into the development branch ?

**Comment by ZhuxiaoLi0113** [comment]
Maybe not now, I would like to clean up a little bit before that. Tim and I
also are waiting for Rashid's response for a group decision. will let you
know later.
Zhuxiao

**Comment by joeschoonover** [comment]
A coupled WAM-IPE run using RC0.0.8 + vertical mixing has been conducted. NetCDF files with output on the fixed height grid can be found under : 
`/scratch4/NCEPDEV/stmp4/Naomi.Maruyama/WAM-IPE/netcdf`
Plots of TEC, NmF2, and Thermosphere temperature can be found under : 
`/scratch4/NCEPDEV/stmp4/Naomi.Maruyama/WAM-IPE/plots`

courtesy of @IonospherePlasmasphereElectrodynamics

**Comment by joeschoonover** [comment]
This is a plot of NmF2 from RC0.0.08 (left) and RC0.0.8+vertical mixing (right) at 0800UT on day 2 of the simulation. The reduction in NmF2 (by roughly a factor of two near the peaks) is a desirable effect with the introduction of vertical mixing to improve mean mass profile.
![screenshot from 2017-11-29 15-15-22](https://user-images.githubusercontent.com/31802478/33402268-4e100790-d519-11e7-963b-6735091e074a.png)

**Comment by timfullerrowell** [comment]
Excellent result. And great to get such a rapid confirmation of impact on
IPE.

Great job everyone!!

**Comment by joeschoonover** [comment]
With the most recent commit from @ZhuxiaoLi0113, new code has been cleaned up and we're ready to merge in.
