### ISSUE TITLE
error message from FLIP solver

### ISSUE THREAD

**Issue by twfang** [SWPC-IPE/WAM-IPE#5]
Some problems show up in FLIP_ERR in my WAM-IPE output folder. Need to be fixed asap. The issue was reported at the hash id dabb473.  
====================================================================
    IN BDSLV &&&&&&& BANDWIDTH IS TOO LARGE        15

  Convergence failure in N+ solution (XION).  Incorrect input to the band solver BDSLV.mp 79lp 12uts=   14    IN BDSuts=   1620      8
uts=   1800      8
uts=   1980      8
uts=   2160      8
uts=   2340      8
uts=   2520      8
uts=   2700      8
uts=   2880      8
uts=   3060      8
uts=   3240      8
uts=   3420      8
onvergence failure in N+ solution (XION).  Incorrect input to the band solver BDSLV.mp 79lp 128     15
    IN BDSLV &&&&&&& BANDWIDTH IS TOO LARGE        15

  Convergence failure in N+ solution (XION).  Incorrect input to the band solver BDSLV.mp 79lp 128     15
    IN BDSLV &&&&&&& BANDWIDTH IS TOO LARGE        15

  Convergence failure in N+ solution (XION).  Incorrect input to the band solver BDSLV.mp 79lp 128     15
    IN BDSLV &&&&&&& BANDWIDTH IS TOO LARGE        15

  Convergence failure in N+ solution (XION).  Incorrect input to the band solver BDSLV.mp 79lp 128     15
    IN BDSLV &&&&&&& BANDWIDTH IS TOO LARGE        15

  Convergence failure in N+ solution (XION).  Incorrect input to the band solver BDSLV.mp 79lp 128     15
    IN BDSLV &&&&&&& BANDWIDTH IS TOO LARGE        15

  Convergence failure in N+ solution (XION).  Incorrect input to the band solver BDSLV.mp 79lp 128     15
    IN BDSLV &&&&&&& BANDWIDTH IS TOO LARGE        15

  Convergence failure in N+ solution (XION).  Incorrect input to the band solver BDSLV.mp 79lp 128     15
    IN BDSLV &&&&&&& BANDWIDTH IS TOO LARGE        15

  Convergence failure in N+ solution (XION).  Incorrect input to the band solver BDSLV.mp 79lp 128     15
    IN BDSLV &&&&&&& BANDWIDTH IS TOO LARGE        15

  Convergence failure in N+ solution (XION).  Incorrect input to the band solver BDSLV.mp 79lp 128     15
    IN BDSLV &&&&&&& BANDWIDTH IS TOO LARGE        15

  Convergence failure in N+ solution (XION).  Incorrect input to the band solver BDSLV.mp 79lp 128     15
~

**Comment by schoonovernumerics** [comment]
With the resolution of issue 9, this error no longer occurs.

**Comment by schoonovernumerics** [comment]
When the restarts occur, IPE's internal "utime" is set to whatever the final time was from the previous run. However, this causes IPE to overwrite the neutrals that were read in from file with unitialized data from the WamField array. To keep this from happening, ut_start_perp_trans is now set to start_time instead of zero. This should allow module_neutral to retain the neutral values that were read in from file.

**Comment by schoonovernumerics** [comment]
This fix resolved the issue. See commit id 6932443
