### ISSUE TITLE
New feature : Variable f10.7 and Kp

### ISSUE THREAD

**Issue by joeschoonover** [SWPC-IPE/WAM-IPE#50]
@twfang and @akubaryk

**Comment by timfullerrowell** [comment]
This is also relevant to WAM. Some of the parameters are not currently include in the XML file transferred from SWPC to WCOSS for the real tim run. The 81-day mean should be variable from day to day, it is current fixed for the 7 day interval of the XML file. The Kp is the integer value 3, 4, 5, etc, it should be the values like 2.33, 2.67, 3.00, 3.33. The average Kp of the previous 24 hours needs to be added for the NO cooling. I will work with DTS to add those parameters. We are also exploring using auroral parameters from ovation to drive the TIROS auroral model in WAM and IPE. Once we settle on the format, we will use the same for historical intervals.

**Comment by joeschoonover** [comment]
This issue should track the development on the rhl_variable_input_parameters branch

**Comment by joeschoonover** [comment]
Currently, IPELIB does not compile (theia intel serial) at commit ID c9a6f8d001121fff266c55c7edc077ec1e668f3c

**Comment by joeschoonover** [comment]
This work is being done in part with Issue #43 . Closing this issue. All comments on this should carry over there.
