### ISSUE TITLE
MS0.6 Crash on WCOSS Real-Time Run

### ISSUE THREAD

**Issue by joeschoonover** [SWPC-IPE/WAM-IPE#55]
This bug is reported on MS0.6, running on WCOSS. This issue was initially brought up by @timfullerrowell on issue #32 , since the bug symptoms were similar. Because Issue #32 was associated with 2-D domain decomposition and MS0.6 is a version before that feature was introduced, the source of the bug is likely from a different source.

### Observed Behavior
Quote from @timfullerrowell on Issue #32 : 
"Houjun's real-time run on WCOSS hit this same MIT error. Occurred in forecast from 03UT after the 21-03, 6 hour cycle. It crashed between 08 and 09UT, just over 5 hours into the forecast. Kp was 0, so very low. The 1 hour run starting at 08UT using real Kp ~2 also had same error. Removing WAM composition produced same error. Theia run also had same error."

**Comment by joeschoonover** [comment]
We need to reproduce this bug in order to confirm we can recreate it.
@gmillward , can you check what's going on with the wam-ipe website ?

**Comment by joeschoonover** [comment]
I suggest we repeat Houjun's run with sw_neutral= 3 (if we can), to use MSIS neutrals to see if the problem is related to neutral fields coming in from WAM.

**Comment by IonospherePlasmasphereElectrodynamics** [comment]
> Removing WAM composition produced same error. 

I would like to be cautious about the test run, because we are not totally sure what kind of initial conditions were used for this test run.

**Comment by joeschoonover** [comment]
I agree, but we need to do something. I think Houjun is restarting his run with sw_neutral=3. Fingers crossed

**Comment by joeschoonover** [comment]
@IonospherePlasmasphereElectrodynamics, what should we do ?

**Comment by joeschoonover** [comment]
@timfullerrowell , can we get the initial conditions that were used for that run ?

**Comment by IonospherePlasmasphereElectrodynamics** [comment]
for the moment, i could think of two hypothesis: (1) the initial conditions could have been already not so good; (2) sudden change from WAM to MSIS( sw_neutral=3) caused the IPE solver to crash.

**Comment by joeschoonover** [comment]
@timfullerrowell has suggested we use Houjun's initial conditions and run a simple forward integration with MS0.6 and our compset scripts.

**Comment by joeschoonover** [comment]
@joeschoonover is tasked with running MS0.6 with sw_neutral=3 (MSIS neutrals), and @akubaryk will run with sw_neutral=0. We'll run with @akubaryk 's latest compset scripts on development

**Comment by timfullerrowell** [comment]
I'll ask Houjun to point us to the initial conditions file on Theia. We could check using 08UT initial conditions first, maybe?

**Comment by joeschoonover** [comment]
When running with Houjun's initial conditions on MS0.6 with `intel/16.1.150 impi netcdf esmf/7.0.0` modules, NEMS immediately crashes with an MPI_Abort error on theia. Additional output includes : 
``` 
[mpiexec@t0839] HYDU_sock_write (../../utils/sock/sock.c:417): write error (Broken pipe)
[mpiexec@t0839] HYD_pmcd_pmiserv_send_signal (../../pm/pmiserv/pmiserv_cb.c:252): unable to write data to proxy
```

**Comment by joeschoonover** [comment]
@akubaryk was able to get a successful run with the parallel scripts

**Comment by joeschoonover** [comment]
Remarks from an e-mail from Houjun : 
" 1) OK, here are the initial conditions for wam and ipe on theia in the following dir (for hourly run)

/scratch3/NCEPDEV/stmp2/swpc.spacepara/prwam.201709nowcast

siganl.gfs.2017103008
sfcanl.gfs.2017103008

RESTART/ipe_grid_neutral_params -> ../2017103007.gfs.ipe_grid_neutral_params.201710300800
RESTART/ipe_grid_plasma_params -> ../2017103007.gfs.ipe_grid_plasma_params.201710300800

& the std output is in the file at the same dir

wam2017103008gfsfcst1_0.dayfile

2) For IPE.inp, find it in RUNDIR (and other namelist too):

/scratch4/NCEPDEV/stmp3/swpc.spacepara/wam2017103008gfsfcst1/IPE.inp

Let me know if I missed anything.

Apparently, If I changed the initial conditions for ipe, I can get it runs now. But it worthwhile to check what bad points are there in the original initial conditions for ipe.

Thanks for looking into this issue. "

**Comment by joeschoonover** [comment]
Running with the "bad" initial conditions in IPE standalone and the IPE.inp file available on MS0.6, the model runs without crashing

**Comment by joeschoonover** [comment]
Using Houjun's IPE.inp file, IPE standalone crashes. @akubaryk is currently running through the parameter differences : 
For reference here's the output of ` diff IPE.inp /scratch3/NCEPDEV/stmp2/swpc.spacepara/prwam.201709nowcast-00/IPE.inp.gfs.2017100605`
```<   f107av=120.0
<   f107d=120.0
---
>   f107av=83
>   f107d=85
41c41
<   nday=71
---
>   nday=279
43c43
<   start_time=432000
---
>   start_time=28800
46,54c46,54
< &nmmsis
<   ap(1)=4.
<   ap(2)=4.
<   ap(3)=4.
<   ap(4)=4.
<   ap(5)=4.
<   ap(6)=4.
<   ap(7)=4.
<   kp_eld=3.
---
>   &nmmsis
>   ap(1)=7
>   ap(2)=7
>   ap(3)=7
>   ap(4)=7
>   ap(5)=7
>   ap(6)=7
>   ap(7)=7
>   kp_eld=2
57c57
<   duration=86400
---
>   duration=43380
67c67
<   record_number_plasma_start=2
---
>   record_number_plasma_start=0
76c76
<   sw_neutral=3
---
>   sw_neutral=1
84c84
<   swEsmfTime=f
---
>   swEsmfTime=t
87a88
>   sw_use_wam_fields_for_restart=t
91c92
<   sw_record_number=0
---
>   sw_record_number=2
93c94
<   ut_start_perp_trans=432000
---
>   ut_start_perp_trans=28800```

**Comment by joeschoonover** [comment]
@akubaryk found that IPE standalone runs once ut_start_perp_trans=432000 and start_time=432000, and fails when both are equal to 28800.

**Comment by wanghj2015** [comment]
Need to start from 28800 for 08UT ICs, not 432000.

**Comment by akubaryk** [comment]
We understand that 28800 corresponds to 08UTC, but it was sufficient to change that to get the model running with the exact same ICs... this is something that needs to be addressed.

**Comment by joeschoonover** [comment]
Agreed - Something is going on in IPE related to the start_time parameter - it should work really for any reasonable start time.

**Comment by wanghj2015** [comment]
also diff with wrong file: not this file
/scratch3/NCEPDEV/stmp2/swpc.spacepara/prwam.201709nowcast-00/IPE.inp.gfs.2017100605
but the file in the rundir from my email

**Comment by wanghj2015** [comment]
It's not surprising if you use different start_time: because you have different solar forcing, that is, ionizing on different or wrong regions.

**Comment by joeschoonover** [comment]
Are you requesting we diff with 
```
/scratch4/NCEPDEV/stmp3/swpc.spacepara/wam2017103008gfsfcst1/IPE.inp 
```
instead ?

**Comment by wanghj2015** [comment]
@akubaryk yes, this is the one that was used and failed.

**Comment by akubaryk** [comment]
Confirmed that coupled WAM-IPE also runs with these initial conditions and start_time!=28800 (0 was used for the test).

The tip of development does not fix the issue; it fails in the same spot when using start_time=28800.

**Comment by akubaryk** [comment]
@joeschoonover reported that the crash does not occur with ipe_grid_plasma_params switched out, indicating the issue is not with the neutrals.

**Comment by joeschoonover** [comment]
This issue has not come up for some time and will be closed for now. (It can be reopened later)
