### ISSUE TITLE
Bring development into master

### ISSUE THREAD

**Issue by joeschoonover** [SWPC-IPE/WAM-IPE#60]
At the request of @rmontuoro, we need to deliver a version release for EMC's Milestone 0.7 . The tasks are 

- [x] Branch off tip of development and tag as release candidate
- [x] Run March 2013 5 day + restart tests out to 10 days on MS0.6 and RC0.0.7 (theia)
- [x] Compare MS0.6 to RC0.0.7  runs
- [x] Debug if necessary
- [x] Merge into Master with new version release

**Comment by joeschoonover** [comment]
This new release will contain modifications for : 
* Vector regridding
* 2-D domain decomposition

**Comment by joeschoonover** [comment]
When running a 5 day test on theia,  the model runs fine for a few iterations, but then crashes with the statement : 
```
 ALLOC PARMS TWRITE          130           2        1351          16           1
  in TWRITES fhour=   1.00000000000000     
 1 end of twritero_rst,SIGR1
 ALLOC PARMS TWRITE          130           2        1351          16           1
  in TWRITES fhour=   1.00000000000000     
 2 end of twritero_rst for SIGR2
 ALLOC PARMS TWRITE          130           2        5109          16           1
forrtl: Too many levels of symbolic links
forrtl: severe (30): open failure, unit 1050, file /scratch3/NCEPDEV/swpc/scrub/Joseph.Schoonover/st
mp/Joseph.Schoonover/rc_test/fort.1051
 ```

I see this error when using the submit.sh script with the following user.config file  :  `/scratch3/NCEPDEV/swpc/noscrub/Joseph.Schoonover/Software/WAM-IPE_MS0.6/scripts/compsets/user.config`

**Comment by joeschoonover** [comment]
I was able to do a 1 hr + restart run on theia with CompsetRun_New. Issue #64 has been opened to resolve the symbolic linking problem.

**Comment by joeschoonover** [comment]
Release candidate test is running and output is under `/scratch3/NCEPDEV/swpc/scrub/Joseph.Schoonover/ptmp/Joseph.Schoonover/rc_test` . This run uses the submit.sh script with the exglobal_fcst_nems.sh modified to copy in the fort.1051 file rather than link. A more permanent solution for this is needed.

**Comment by joeschoonover** [comment]
New 5 day run with march 2013 initial conditions on theia has been submitted on the release_candidate branch (hash id : 4c24c7e853a4a9978893c28c587d46d426938df9 ). Model output is under : 
`/scratch3/NCEPDEV/swpc/scrub/Joseph.Schoonover/ptmp//Joseph.Schoonover/march2013_regression`

**Comment by joeschoonover** [comment]
Still experiencing the error with fort.1051 : 
```
forrtl: Too many levels of symbolic links
forrtl: severe (30): open failure, unit 1050, file /scratch3/NCEPDEV/swpc/scrub/Joseph.Schoonover/stmp/Joseph.Schoonover/march2013_regression/fort.1051
```

**Comment by joeschoonover** [comment]
This has been fixed after bringing in updated scripts from development. 5 day run on theia is complete. Just submitted for restart run

**Comment by joeschoonover** [comment]
To do the test on MS0.6, I need to use the same compset scripts as is used in RC0.0.8. To do this, after checking out the MS0.6 tag 
```
git checkout tags/MS0.6 -b MS0.6
```
I've checked out the scripts from the release_candidate branch at the same location as the RC0.0.8 tag 
```
git checkout remotes/origin/release_candidate -- scripts
```

**Comment by joeschoonover** [comment]
Also needed to update modulefiles/theia/wam-ipe to point to esmf/7.0.2 in order to compile correctly on thei

**Comment by joeschoonover** [comment]
RC0.0.8 required 5hr 10min 57sec to complete 5 days of simulation with files output once every simulation hour

**Comment by joeschoonover** [comment]
ms0.6 required 4hr  25min 9sec to complete 5 days of simulation with identical configuration to RC0.0.8

**Comment by joeschoonover** [comment]
Note that in RC0.0.8, the fp-model strict flag is on. Although this flag is needed for bit-for-bit reproducibility of results, such precision may not be necessary for production runs.

**Comment by joeschoonover** [comment]
Plots and NetCDF files for the RC0.0.8 run with `fp-model strict` can be found under : 
/scratch3/NCEPDEV/swpc/noscrub/Joseph.Schoonover/march2013_RC0.0.8_O3_fp-model_strict/netcdf/

**Comment by joeschoonover** [comment]
Restart run of ms0.6 took 4hr 30min 7sec

**Comment by joeschoonover** [comment]
Restart run of RC0.0.8 (with `-fp-model strict`) took 5hr 17min 17sec

**Comment by joeschoonover** [comment]
Removing the `-fp-model strict` flag reduced the RC0.0.8 wall time to 4hr 22min 17sec , indicating that the increased run in RC0.0.8 time was a result of the more costly floating point operations enforced by this flag.

**Comment by joeschoonover** [comment]
Model output ( March 2013 Initial Conditions, 10 day simulation, WAM-IPE ) is archived under my `swpc/noscrub` directories : 
MS0.6  : 
```
/scratch3/NCEPDEV/swpc/noscrub/Joseph.Schoonover/march2013_ms0.6/output
```
RC0.0.8 ( with `-fp-model strict` )
```
/scratch3/NCEPDEV/swpc/noscrub/Joseph.Schoonover/march2013_RC0.0.8_O3_fp-model_strict/output
```
RC0.0.8 ( without -fp-model strict )
```
/scratch3/NCEPDEV/swpc/noscrub/Joseph.Schoonover/march2013_RC0.0.8_O3/output
```

**Comment by joeschoonover** [comment]
I've started a summary document comparing these three runs that can be found here : https://drive.google.com/a/noaa.gov/file/d/1auLj8hvXer6vE1bwPgT7r6xNEJN0rr9K/view?usp=sharing

what remains is to fill in the difference tables using the ncap2 scripts.

**Comment by akubaryk** [comment]
The current `release_candidate` branch includes Weiyu's changes (commits `8dc0612` and `ccf9d7e`) for two-way coupling, which should have no impact on the results, but also Rashid's `idea_tracer_eddy` routine, which likely contributes to the substantial differences observed between MS0.6 and the current release candidate. The last commit prior to these is `e824633`.

**Comment by joeschoonover** [comment]
Because of this, I'm going to delete the current release_candidate branch and make a new one off of e824633

**Comment by joeschoonover** [comment]
New RC0.0.9 tag has been created after reverting those commits
