### ISSUE TITLE
Domain Decomposition Bug : Nodes no element association

### ISSUE THREAD

**Issue by joeschoonover** [SWPC-IPE/WAM-IPE#62]
### Observed Behavior
On the raw_high_lat branch we are using a 58x8 domain decomposition with a load_balance_groups file that results in some ranks receiving a single row of nodes. After executing WAM-IPE with the submit.sh script, the following errors are seen 

When running grep ERROR PET* in the output directory, similar messages to this show up :
```
PET468.ESMF_LogFile:20171106 213853.640 ERROR            PET468 /tds_scratch3/SYSADMIN/nesccmgmt/Raghu.Reddy/theia-builds/esmf_7_0_0_src/src/Infrastructure/Mesh/src/ESMCI_Mesh_Glue.C:878 c_esmc_meshcreate() Value unrecognized or out of range  - - there are nodes on this PET that were not used in the element connectivity list
PET468.ESMF_LogFile:20171106 213853.650 ERROR            PET468 /tds_scratch3/SYSADMIN/nesccmgmt/Raghu.Reddy/theia-builds/esmf_7_0_0_src/src/Infrastructure/Mesh/src/ESMCI_Mesh_Glue.C:1401 c_esmc_meshcreate() Value unrecognized or out of range  - Internal subroutine call returned Error
PET468.ESMF_LogFile:20171106 213853.650 ERROR            PET468 ESMF_Mesh.F90:689 ESMF_MeshAddElements() Value unrecognized or out of range  - Internal subroutine call returned Error
PET468.ESMF_LogFile:20171106 213853.650 ERROR            PET468 ipeCap.F90:689 IPECap::InitializeRealize::IPEMe Value unrecognized or out of range  - Passing error in return code
PET468.ESMF_LogFile:20171106 213853.650 ERROR            PET468 ipeCap.F90:292 Value unrecognized or out of range  - Passing error in return code
PET468.ESMF_LogFile:20171106 213853.650 ERROR            PET468 EARTH grid component01:src/addon/NUOPC/src/NUOPC_Driver.F90:1238 Value unrecognized or out of range  - Phase 7 Initialize for modelComp 3: IPM did not return ESMF_SUCCESS
PET468.ESMF_LogFile:20171106 213853.650 ERROR            PET468 EARTH grid component01:src/addon/NUOPC/src/NUOPC_Driver.F90:770 Value unrecognized or out of range  - Passing error in return code
PET468.ESMF_LogFile:20171106 213853.650 ERROR            PET468 module_NEMS_GRID_COMP.F90:666 Value unrecognized or out of range  - Breaking out of subroutine
```

In email communications, @oehmke remarked : 
"   I took a look at the ESMF error messages. What’s happening is that there are Mesh nodes (i.e. corners) being created on a processor without an associated Mesh element (i.e. cell). This isn’t allowed in an ESMF Mesh. Every node needs an associated element “home” on a processor. As Raffaele, and others speculated this is likely because the Mesh is being divided so there is only one row of nodes on a processor. 

Raffaele, a solution to this is create a copy of the element on each of the processors where a node needs a host, so that the node that now doesn’t have a local element has one. 

For example, take this simple Mesh with node ids in the corners and element ids in the center. 
```
 1 - - - 2 - - - 3
 |       |       |
 |   1   |   2   |
 |       |       |
 4 - - - 5 - - - 6
```

To divide this across 3 processors you could do something like the following, where the [] around a node indicate that the node is a ghost node not local to the processor:

```
 1 - - - [2]     2 - - - [3]    [2] - - - 3
 |        |      |        |      |        |
 |   1    |      |   2    |      |    2   | 
 |        |      |        |      |        |
 4 - - - [5]     4 - - - [6]    [4] - - - 6

    proc 0         proc 1           proc 2
```
"

**Comment by joeschoonover** [comment]
This bug was first reported in Issue #43

**Comment by joeschoonover** [comment]
@rmontuoro , in your experience, does that commit resolve the issue ? I've just pulled it down for testing

**Comment by rmontuoro** [comment]
The source of this issue was tentatively attributed to the IPE NUOPC Cap based on the logged error messages, since no debugging could be carried out due to the scheduled NESCC systems maintenance on November 7. Once access to Theia was restored, tests traced back this issue to the following missing lines in [](https://github.com/SWPC-IPE/WAM-IPE/blob/raw_high_lat/IPELIB/src/main/module_input_parameters.f90), which should have been moved over from the development branch:
```
        ! convert min/max mesh height from km to meters
        mesh_height_min = 1.e+03_real_prec * mesh_height_min
        mesh_height_max = 1.e+03_real_prec * mesh_height_max
```
Since both mesh_height_min and mesh_heigh_max are entered in km (but used in m internally), the lack of conversion caused most of the plasma grid points not to be added to the ESMF Mesh object.

Below is a picture of the resulting IPE mesh after commit 110f7ac4e1a9b46b080f79c524c3abaeebc6b0a3

<img width="861" alt="ipe_mesh" src="https://user-images.githubusercontent.com/18299064/32564966-632b7c1c-c47b-11e7-8ac4-c34b9fdd706c.png">

**Comment by joeschoonover** [comment]
Nice. I'll let you know if I can get a successful run out for both IPE standalone and WAM-IPE after compiling finishes

**Comment by joeschoonover** [comment]
This seems to resolve the issue described here. Thanks @rmontuoro
