### ISSUE TITLE
Bug in exglobal_fcst_nems.sh

### ISSUE THREAD

**Issue by joeschoonover** [SWPC-IPE/WAM-IPE#63]
### Observed Behavior
When  attempting to run a simulation with submit.sh, the model runs through initialization but then crashes with the statement : 
```
  ALLOC PARMS TWRITE          130           2        1351          16           1
  in TWRITES fhour=   1.00000000000000     
 1 end of twritero_rst,SIGR1
 ALLOC PARMS TWRITE          130           2        1351          16           1
  in TWRITES fhour=   1.00000000000000     
 2 end of twritero_rst for SIGR2
 ALLOC PARMS TWRITE          130           2        5109          16           1
forrtl: Too many levels of symbolic links
forrtl: severe (30): open failure, unit 1050, file /scratch3/NCEPDEV/swpc/scrub/Joseph.Schoonover/st
mp/Joseph.Schoonover/rc_test/fort.1051
```

Performing an `ls -l fort.1051` in the stmp directory yields
```
Too many levels of symbolic links
```

When attempting to understand where the layers of symbolic links point using `tree`, I see the following : 
```
[Joseph.Schoonover@tfe07 development_test]$ tree fort.1051
fort.1051 [error opening dir]

0 directories, 0 files
```

Hard coding this file to copy in rather than link avoids this error and the model runs as expected. 

A new branch has been created (compset_bug_fix) for us to work on a clean solution to this bug.

**Comment by akubaryk** [comment]
This is new behavior since the Theia maintenance period this week. Currently submitting a run to start the debugging process.

**Comment by akubaryk** [comment]
Turns out to have nothing to do with Theia.

There were conditions causing a circular `ln` reference due to shoddy logic in the config files. This has been rectified with commit `71d4d5e`. Merging into development.

**Comment by akubaryk** [comment]
Pull request has been completed.
