### ISSUE TITLE
WAM Standalone does not compile after Theia upgrade

### ISSUE THREAD

**Issue by joeschoonover** [SWPC-IPE/WAM-IPE#65]
### Observed Behavior
After the theia upgrade, we should switch to ESMF/7.0.2 rather than ESMF/7.0.0. When running
```
NEMS/NEMSAppBuilder rebuild app=wam-ipe
```
the source code compiles correctly.

When using
```
NEMS/NEMSAppBuilder rebuild app=standaloneGSM
```
to compile for standalone WAM, the make system tries to load esmf/7.0.0 which causes the build system to crash.

The make system indicates 
```
NOTE: Load /scratch3/NCEPDEV/swpc/noscrub/Joseph.Schoonover/Software/WAM-IPE/NEMS/src/conf/modules.nems
Lmod has detected the following error:  The following module(s) are unknown:
"esmf/7.0.0"
```
just before the crash, suggesting that we need to set up ` NEMS/src/conf/modules.nems` to point to esmf/7.0.2 . A new branch (wam_build_fix) is being created to patch this bug.

**Comment by joeschoonover** [comment]
I attempted to manually change the module load statement in modules.nems, but the build system overwrote them. This setting is being propagated from somewhere else.

**Comment by samtrahan** [comment]
The files you need to change are in modulefiles/theia.  They're copied to the NEMS/src/conf/ directory by the NEMSAppBuilder.

**Comment by joeschoonover** [comment]
I did that already. We can compile WAM-IPE, but for some reason standaloneGSM isn't working

**Comment by joeschoonover** [comment]
Should the rest of those under there also be updated then ?

**Comment by samtrahan** [comment]
Do you have logs I can look at?

**Comment by joeschoonover** [comment]
`/scratch3/NCEPDEV/swpc/noscrub/Joseph.Schoonover/Software/WAM-IPE/log`

**Comment by samtrahan** [comment]
Yes, everything in that directory needs to be updated.  If the standaloneGSM is using another modulefile, it would explain the problem.

**Comment by joeschoonover** [comment]
Perfect. Just updated all of them to point to esmf/7.0.2 and it seems to be working now.

**Comment by samtrahan** [comment]
Excellent.  I'm glad you fixed it.

**Comment by joeschoonover** [comment]
Thanks for pointing me in the right direction. Merging into development...
