### ISSUE TITLE
IPE data output takes too long - speed up needed

### ISSUE THREAD

**Issue by gmillward** [SWPC-IPE/WAM-IPE#68]
The output of plasma and neutral parameters takes too long - especially on WCOSS - outputting at 15 minute cadence increases model run time by a third.

The data being outputted every 15 mins is identical to the IPE restart files - but for graphics purposes we can do something much faster.

Need to think this through - has major implications for CONOPS - but, in general, we do not need to write out full restart datasets just for the benefit of graphics.
....but the CONOPS might dictate that we need to output these files with an even higher cadence.

**Comment by joeschoonover** [comment]
To resolve this issue, we likely just want to output our products every fifteen minutes and write pickup files at longer intervals. We still need a list of products. This work can be a part of the IPE refactoring

**Comment by joeschoonover** [comment]
Additionally, in-Situ visualization can further alleviate this problem. I can provide a plan for doing in-situ visualization and estimate the effort necessary to see if this is something we want to tackle in quarter 2.

**Comment by joeschoonover** [comment]
With the refactored code now in place, IPE initialization and File IO time should be documented in order to determine clear conditions for satisfaction.
