### ISSUE TITLE
New Mediator

### ISSUE THREAD

**Issue by joeschoonover** [SWPC-IPE/WAM-IPE#70]
The new mediator will be brought in to replace the current mediator. Completion of this issue involves completion of the following tasks :

- [x] Make a new branch off of development and bring in new mediator code
- [x] Document any new switches, namelist parameters, environment variables needed to configure the new mediator
- [x] Run coupled simulations with one way coupling and reproduce previous version results 
- [x] Debug if needed
- [x] Merge into development

**Comment by joeschoonover** [comment]
Here are additional subtasks  : 

- [ ] Conduct 1-hr V0.2 simulations with 1x80, 2x40, 4x20, and 8x10 domain decompositions and report wall-times to this issue tracker
- [ ] Conduct 1-hr updated_mediator simulations with 1x80, 2x40, 4x20, and 8x10 domain decompositions and report the wall-times to this issue tracker
- [ ] Decide on configuration to use for 5 day + restart
- [ ] Run V0.2 5 day + restart
- [ ] Run updated_mediator 5 day + restart
- [ ] Check for bit-for-bit reproducibility between V0.2 and updated_mediator, reporting results to this issue tracker

**Comment by joeschoonover** [comment]
Here are the directories containing output for the old mediator simulation : 

1x80
```
/scratch3/NCEPDEV/swpc/scrub/Joseph.Schoonover/ptmp/Joseph.Schoonover/march2013_old_mediator_1x80_1hr
```
2x40
```
/scratch3/NCEPDEV/swpc/scrub/Joseph.Schoonover/ptmp/Joseph.Schoonover/march2013_old_mediator_2x40_1hr
```
4x20
```
/scratch3/NCEPDEV/swpc/scrub/Joseph.Schoonover/ptmp/Joseph.Schoonover/march2013_old_mediator_4x20_1hr
```
8x10
```
/scratch3/NCEPDEV/swpc/scrub/Joseph.Schoonover/ptmp/Joseph.Schoonover/march2013_old_mediator_8x10_1hr
```

**Comment by joeschoonover** [comment]
The wall-times for each simulation are : 
1x80 : 5 min 3 sec
2x40 : 6 min 20 sec
4x20 : 7 min 31 sec
8x10 :  8 min 4 sec

**Comment by joeschoonover** [comment]
Based on these runs alone, I'd be inclined to use the 1x80 simulation for the 5 day runs.

**Comment by joeschoonover** [comment]
How can I verify that the old mediator has been used ?

**Comment by rmontuoro** [comment]
The old mediator will write to standard output the following lines:

1. `MED Advance() mediating for:` at each coupling time step
2. `Complete MEDIATOR` at the end of the run

The updated mediator will write to standard output:

1. `------>Advancing Mediator from: ` at each coupling step
2. A lot of debugging information about fields and grid/mesh objects

**Comment by joeschoonover** [comment]
Based on the standard output files, it looks like setting that environment variable in the configuration script selected the correct mediator

**Comment by rmontuoro** [comment]
Output from 1-hr simulations with new and old mediator can be found in the directories below.

*New mediator*

```
/scratch3/NCEPDEV/swpc/scrub/Raffaele.Montuoro/ptmp/Raffaele.Montuoro/march2013_updated_mediator_1x80_1hr
/scratch3/NCEPDEV/swpc/scrub/Raffaele.Montuoro/ptmp/Raffaele.Montuoro/march2013_updated_mediator_2x40_1hr
/scratch3/NCEPDEV/swpc/scrub/Raffaele.Montuoro/ptmp/Raffaele.Montuoro/march2013_updated_mediator_4x20_1hr
/scratch3/NCEPDEV/swpc/scrub/Raffaele.Montuoro/ptmp/Raffaele.Montuoro/march2013_updated_mediator_8x10_1hr
```
Timings:
```
1x80: 00:04:51
2x40: 00:06:15
4x20: 00:07:34
8x10: 00:08:03
```

*Old mediator*

```
/scratch3/NCEPDEV/swpc/scrub/Raffaele.Montuoro/ptmp/Raffaele.Montuoro/march2013_old_mediator_1x80_1hr
/scratch3/NCEPDEV/swpc/scrub/Raffaele.Montuoro/ptmp/Raffaele.Montuoro/march2013_old_mediator_2x40_1hr
/scratch3/NCEPDEV/swpc/scrub/Raffaele.Montuoro/ptmp/Raffaele.Montuoro/march2013_old_mediator_4x20_1hr
/scratch3/NCEPDEV/swpc/scrub/Raffaele.Montuoro/ptmp/Raffaele.Montuoro/march2013_old_mediator_8x10_1hr
```

Timings:
```
1x80: 00:04:55
2x40: 00:06:19
4x20: 00:07:30
8x10: 00:08:01
```

**Comment by joeschoonover** [comment]
I've compared your old_mediator 1x80 with all of the updated_mediator configurations, and I'm seeing bitwise reproducibility.

**Comment by joeschoonover** [comment]
Given that the 1x80 yields the lowest run-time, let's push forward with the 5 day simulations for the old and new mediators using that configuration

**Comment by rmontuoro** [comment]
5-day 1x80 simulations with the old and new mediator have completed on Theia. However, the old mediator simulation only ran for about 4 days and 10 hours due to a too short wall time set. Output directories are included below:

**New mediator**
```
/scratch3/NCEPDEV/swpc/scrub/Raffaele.Montuoro/ptmp/Raffaele.Montuoro/march2013_updated_mediator_1x80_5d/
```
**Old mediator**
```
/scratch3/NCEPDEV/swpc/scrub/Joseph.Schoonover/ptmp/Joseph.Schoonover/march2013_old_mediator_1x80_5day/
```

Out of 108 common output neutral files, only 27 are *not* bitwise identical. These differences are being investigated. The affected files are listed below:

```
ipe_grid_neutral_params.201303160300
ipe_grid_neutral_params.201303160600
ipe_grid_neutral_params.201303160700
ipe_grid_neutral_params.201303161300
ipe_grid_neutral_params.201303161600
ipe_grid_neutral_params.201303161700
ipe_grid_neutral_params.201303161800
ipe_grid_neutral_params.201303162100
ipe_grid_neutral_params.201303170600
ipe_grid_neutral_params.201303171100
ipe_grid_neutral_params.201303171200
ipe_grid_neutral_params.201303171300
ipe_grid_neutral_params.201303171500
ipe_grid_neutral_params.201303171700
ipe_grid_neutral_params.201303171800
ipe_grid_neutral_params.201303171900
ipe_grid_neutral_params.201303180400
ipe_grid_neutral_params.201303181200
ipe_grid_neutral_params.201303181700
ipe_grid_neutral_params.201303182000
ipe_grid_neutral_params.201303190000
ipe_grid_neutral_params.201303191800
ipe_grid_neutral_params.201303192000
ipe_grid_neutral_params.201303192100
ipe_grid_neutral_params.201303192200
ipe_grid_neutral_params.201303192300
ipe_grid_neutral_params.201303200400
```

**Comment by joeschoonover** [comment]
Below shows min and max differences (first two columns), and the max value of the variable from the old-mediator run (third column) for some of the files that show differences (not bitwise identical) 
```
ipe_grid_neutral_params.201303160300
-----------------------
 DIFF REP : temp_neutral  0.0000000E+00  0.0000000E+00   1203.440    
 DIFF REP : wind_neutral: u  0.0000000E+00  0.0000000E+00   302.2273    
 DIFF REP : wind_neutral: v  0.0000000E+00  0.0000000E+00   250.4306    
 DIFF REP : wind_neutral: w  0.0000000E+00  1.1368684E-13   19.17876    
 DIFF REP : O_Density  0.0000000E+00  0.0000000E+00  2.7525281E+18
 DIFF REP : N2_Density  0.0000000E+00  0.0000000E+00  7.7429007E+19
 DIFF REP : O2_Density  0.0000000E+00  0.0000000E+00  2.0227938E+19
-----------------------
ipe_grid_neutral_params.201303160600
-----------------------
 DIFF REP : temp_neutral  0.0000000E+00  0.0000000E+00   1212.257    
 DIFF REP : wind_neutral: u  0.0000000E+00  0.0000000E+00   365.9726    
 DIFF REP : wind_neutral: v  0.0000000E+00  0.0000000E+00   355.6774    
 DIFF REP : wind_neutral: w  0.0000000E+00  5.6843419E-14   8.939237    
 DIFF REP : O_Density  0.0000000E+00  0.0000000E+00  2.5949920E+18
 DIFF REP : N2_Density  0.0000000E+00  0.0000000E+00  7.6731899E+19
 DIFF REP : O2_Density  0.0000000E+00  0.0000000E+00  2.0110791E+19
-----------------------
ipe_grid_neutral_params.201303160700
-----------------------
 DIFF REP : temp_neutral  0.0000000E+00  0.0000000E+00   1206.182    
 DIFF REP : wind_neutral: u  0.0000000E+00  1.1920929E-07   387.4908    
 DIFF REP : wind_neutral: v  0.0000000E+00  0.0000000E+00   321.9868    
 DIFF REP : wind_neutral: w  0.0000000E+00  0.0000000E+00   7.591109    
 DIFF REP : O_Density  0.0000000E+00  0.0000000E+00  2.5135878E+18
 DIFF REP : N2_Density  0.0000000E+00  0.0000000E+00  7.6821620E+19
 DIFF REP : O2_Density  0.0000000E+00  0.0000000E+00  2.0177982E+19
-----------------------
ipe_grid_neutral_params.201303161300
-----------------------
 DIFF REP : temp_neutral  0.0000000E+00  0.0000000E+00   1170.196    
 DIFF REP : wind_neutral: u  0.0000000E+00  0.0000000E+00   227.2324    
 DIFF REP : wind_neutral: v  0.0000000E+00  7.4505806E-09   356.5631    
 DIFF REP : wind_neutral: w  0.0000000E+00  0.0000000E+00   8.379679    
 DIFF REP : O_Density  0.0000000E+00  0.0000000E+00  2.4346296E+18
 DIFF REP : N2_Density  0.0000000E+00  0.0000000E+00  7.4850934E+19
 DIFF REP : O2_Density  0.0000000E+00  0.0000000E+00  1.9641924E+19
```

It appears that the differences are round off errors

**Comment by joeschoonover** [comment]
At this point, we're ready to open a pull request
