### ISSUE TITLE
IPELIB SMS Compile Error message

### ISSUE THREAD

**Issue by schoonovernumerics** [SWPC-IPE/WAM-IPE#8]
![screenshot from 2017-08-28 13-13-48](https://user-images.githubusercontent.com/11430768/29789308-d4fb7692-8bf2-11e7-9c42-15961f3a84f3.png)

During the build of IPELIB, the above error is reported from SMS. The error also appears when compiling IPE standalone with parallelism enabled. 
This error is not fatal and does not stop compilation, but is an issue that needs to be addressed.

**Comment by akubaryk** [comment]
Issue have been resolved. We still have some remaining build warnings, though:
```
defined(@array) is deprecated at /scratch3/NCEPDEV/swpc/noscrub/sms/SMSr825-intel_14.0.2-mpi_5.1.2.150/bin/ppp line 102.`
        (Maybe you should just omit the defined()?)
```

and

```
module_read_plasma_grid_global_sms.f90: warning #5462: Global name too long, shortened from: module_read_plasma_grid_global_mp_read_plasma_grid_global_$BLK.module_input_parameters_mp_mpi_argvs_null_ to: ad_plasma_grid_global_mp_read_plasma_grid_global_$BLK.module_input_parameters_mp_mpi_argvs_null_
# 1 "module_read_plasma_grid_global_sms.f90"
^
```

**Comment by joeschoonover** [comment]
There are plans to remove our dependency on SMS by January. SMS is no longer a supported library and NCO will likely not accept the code with a dependency on SMS. Those additional warning messages will be gone when that transition is complete.
