### ISSUE TITLE
WamField not updating

### ISSUE THREAD

**Issue by schoonovernumerics** [SWPC-IPE/WAM-IPE#9]
When running CompsetRun_New on theia, it was first noticed in the ipe_grid_neutral_params files that the neutrals were not being updated. Min/Max checks were inserted inside of IPELIB/src/neutral/module_neutral.f90 and it was confirmed that neutral_parameters continued to have the same value every time step. Within module_neutral, the IPE neutral fields are supposed to be updated with the array WamField, which is, in turn, updated in IPE/ipeCap.F90 on lines 1419-1426.

It is unclear if the WamField is actually updated by the ESMF call.

**Comment by schoonovernumerics** [comment]
![screenshot from 2017-08-28 15-48-36](https://user-images.githubusercontent.com/11430768/29795191-6da5084e-8c08-11e7-872d-c14256759f6e.png)
This screenshot shows the top section of the neutral subroutine that is executed within WAM-IPE.
Notice that the neutrals fields are updated with msis fields when utime = ut_start_perp_trans, and with WAM fields when utim > ut_start_perp_trans (that's what's happening below line 218.

**Comment by schoonovernumerics** [comment]
![screenshot from 2017-08-28 15-23-04](https://user-images.githubusercontent.com/11430768/29795264-bd199304-8c08-11e7-8696-4ad6c627ee25.png)
Print statements are inserted, showing the min/max of the local neutral fields and the incoming wamfields. "in neutral 1" shows the min/max values before executing any statements in the neutral subroutine, and "in neutral 2" shows the min/max values at the end of the neutral subroutine.

 These arrays show different min/max values by the end of the second time steps, indicating the local neutrals are not being updated by wamfield. Notice that the utime starts at zero. However, IPE.in sets ut_start_perp_trans = 432000, thus none of the statements get executed.

To fix this temporarily, ut_start_perp_trans is set to 0 on line 326 in the IPE/module_sub_myIPE_Init.F90.
This fix may not be ideal, but others should contribute on what the ideal fix should be.

**Comment by schoonovernumerics** [comment]
![screenshot from 2017-08-28 16-26-38](https://user-images.githubusercontent.com/11430768/29796336-c0e5d358-8c0d-11e7-8953-a2d2cb5394c9.png)
this is a similar screenshot to the previous post, except with the suggested fix. The neutrals are updating

**Comment by schoonovernumerics** [comment]
This fix was pushed to the development branch of the repository with commit id e815297

**Comment by oehmke** [comment]
Would setting ut_start_perp_trans =0 in IPE.inp work too? I already have a separate IPE.inp that George gave me for coupled runs, so it would be pretty easy to just have that always be 0.

**Comment by schoonovernumerics** [comment]
That would be a good change, so that we don't have to hard-code this fix into the source code.
I take it that there is a spot that the IPE.inp file is copied from for the coupled runs? If so, let's go ahead and do that, and then I'll remove my change to IPE/module_sub_myIPE_Init.F90

**Comment by oehmke** [comment]
It's copying: /scratch3/NCEPDEV/swpc/noscrub/Robert.Oehmke/IPE_IC/input_files/IPE.inp-ops
(We should eventually put this next to the other IPE ICs, but let's get things working first and then talk about where to put it, since it's not as specific as the other IPE.inp s) 

I just changed ut_start_perp_trans =0 in there, do you want to try rerunning to see if it fixes the problem.

**Comment by schoonovernumerics** [comment]
Yea, I'll give that a try

**Comment by schoonovernumerics** [comment]
Does the compset script always copy from there ?

**Comment by oehmke** [comment]
Yep.

 In George's other version this file was in a directory under IPE in the source code, but somehow that didn't make it into the version that got checked in. We should talk about where it should end up eventually...

**Comment by schoonovernumerics** [comment]
That IPE.inp-ops file should be a part of the repository. Where in the compset script is that set ?

**Comment by oehmke** [comment]
I agree. 

It's in CompsetRun_New in new_restart_ipe() and new_setup_ipe() and setup_ipe() (which points to George's old source code).

**Comment by IonospherePlasmasphereElectrodynamics** [comment]
This meant to be the bug report for our record.

![swpc_20130316_2day_spacewx_gsm_wam_t62_ipe_80x170_restart_on_m3_ht350 mag quick](https://user-images.githubusercontent.com/13737186/29797488-8fdd8d6c-8c14-11e7-9e85-56dda588e637.png)
neutral atomic oxygen density was plotted from bob's 2day restart run: /scratch3/NCEPDEV/swpc/scrub/Robert.Oehmke/rt_123589/swpc%20130316_2day_spacewx_gsm%wam%T62_ipe%80x170_restart/. 

It was confirmed that WAM field , at least Tn and [O], are not updating for 2days.

**Comment by schoonovernumerics** [comment]
Let's think on how to incorporate these fixes cleanly. I'll prepare some suggestions for the directory structure in WAM-IPE that may be a part of this fix...

**Comment by IonospherePlasmasphereElectrodynamics** [comment]
The problem happened partly because this parameter, "ut_start_perp_trans" was not so visible to users, and also no documentation about the parameter. Wherever it will end up being in the code/script, we should make sure that the documentation/explanation of the parameter should be very visible to users.

**Comment by oehmke** [comment]
I agree to both. If this file really doesn't change no matter what coupled run you do (is that actually true?), maybe the best long term solution would be to get rid of it when running coupled and have things set up internally.

**Comment by schoonovernumerics** [comment]
This only became a problem when we brought in the new IPE cap, and we were not aware that "utime" was started at zero when running coupled WAM-IPE. This is why the initial fix was to overwrite ut_start_perp_trans within the intialization stage of IPE when coupled.

**Comment by schoonovernumerics** [comment]
For now, I'm going to close this issue, since we have addressed the initial problem.
